{
  "hash": "d1081b34b4da0d2a9fbe272f95a6a2d0",
  "result": {
    "engine": "knitr",
    "markdown": "# Analysis of variance {#sec-chap07}\n\n\n\n\n\n## Achievements to unlock\n\n::: my-objectives\n::: my-objectives-header\nObjectives\n:::\n\n::: my-objectives-container\n**SwR Achievements**\n\n- **Achievement 1**: Exploring the data using graphics and descriptive statistics {@sec-chap07-achievement1}\n- **Achievement 2**: Understanding and conducting one-way ANOVA {@sec-chap07-achievement2}\n- **Achievement 3**: Choosing and using post hoc tests and contrasts {@sec-chap07-achievement3}\n- **Achievement 4**: Computing and interpreting effect sizes for ANOVA {@sec-chap07-achievement4}\n- **Achievement 5**: Testing ANOVA assumptions {@sec-chap07-achievement5}\n- **Achievement 6**: Choosing and using alternative tests when ANOVA assumptions are not met {@sec-chap07-achievement6}\n- **Achievement 7**: Understanding and conducting two-way ANOVA {@sec-chap07-achievement7}\n\n:::\n:::\n\n<a class='glossary' title='Analysis of variance is a statistical method used to compare means across groups to determine whether there is a statistically significant difference among the means; typically used when there are three or more means to compare. (SwR, Glossary)'>ANOVA</a> is the statistical method used for comparing means across three or more groups. \n\n- Like the <a class='glossary' title='Student t-test is a statistical test used to test whether the difference between the response of two groups is statistically significant or not. (Wikipedia)'>t-test</a>, ANOVA has underlying assumptions.\n- Similar to <a class='glossary' title='Chi-squared is the test statistic following the chi-squared probability distribution; the chi-squared test statistic is used in inferential tests, including examining the association between two categorical variables and determining statistical significance for a logistic regression model. (SwR, Glossary)'>chi-squared</a>, ANOVA is an <a class='glossary' title='An omnibus is a statistical test that identifies that there is some relationship going on between variables, but not what that relationship is. (SwR, Glossary)'>omnibus</a> test.\n- Instead of using <a class='glossary' title='Standardized residuals are the standardized differences between observed and expected values in a chi-squared analysis; a large standardized residual indicates that the observed and expected values were very different. (SwR, Glossary)'>standardized residuals</a>, ANOVA uses planned contrasts and post hoc tests.\n- Instead of <a class='glossary' title='Cramér’s V is an effect size to determine the strength of the relationship between two categorical variables; often reported with the results of a chi-squared. (SwR, Glossary)'>Cramér’s V</a> or <a class='glossary' title='Odds is usually defined in statistics as the probability an event will occur divided by the probability that it will not occur. An odds ratio (OR) is a measure of association between a certain property A and a second property B in a population. Specifically, it tells you how the presence or absence of property A has an effect on the presence or absence of property B. (Statistics How To). An odds ratio is a ratio of two ratios. They quantify the strength of the relationship between two conditions. They indicate how likely an outcome is to occur in one context relative to another. (Statistics by Jim)'>odds ratios</a> for chi-squared and <a class='glossary' title='Cohen’s d is a standardized effect size for measuring the difference between two group means. It is frequently used to compare a treatment to a control group. It can be a suitable effect size to include with t-test and ANOVA results. (Statistics by Jim)'>Cohen’s d</a> for t-tests, $η^2$ and $ω^2$ are often reported as <a class='glossary' title='Effect size is a measure of the strength of a relationship; effect sizes are important in inferential statistics in order to determine and communicate whether a statistically significant result has practical importance. (SwR, Glossary)'>effect sizes</a> for ANOVA.\n\n\n## The technical difficulties problem (empty)\n\n## Resources & Chapter Outline\n\n### Data, codebook, and R packages {#sec-chap04-data-codebook-packages}\n\n::: my-resource\n::: my-resource-header\nData, codebook, and R packages for learning about descriptive statistics\n:::\n\n::: my-resource-container\n\n**Data**\n\n\nTwo options:\n\n1. Download the `gss2018.rda` data set from <https://edge.sagepub.com/harris1e>.\n2. Use {**gssr**} to download the year 2018.\n\n(As a direct download with the {**gssr**} package results in labelled data with different column names and the necessary transformation will not gain any additional knowledge for me, I will take the `gss2018.rda` data set from the book.)\n\n**Codebook**\n\nTwo options:\n\n1. Access variable documentation (not a full codebook) on the GSS Data Explorer website at <https://gssdataexplorer.norc.org/> \n2. Use the help pages from {**gssr**} package.\n\n\n**Packages**\n\n1. Packages used with this chapter (sorted alphabetically)\n\n-   {**tidyverse**}: @pak-tidyverse (Hadley Wickham)\n-   {**car**): @pak-car (John Fox)\n-   {**dunn.test**} @pak-dunn.test (Alexis Dinno)\n\n    \n2. My additional packages (sorted alphabetically)\n\n\n\n:::\n:::\n\n\n\n### Get data {#sec-chap07-get-data}\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap07-get-gss2018-book}\n: Get book GSS data set `gss2018.rda` and save it as `gss_2018.rds`\n::::::\n:::\n::::{.my-r-code-container}\n\n::: {.cell}\n\n```{.r .cell-code}\n## run only once (manually)\n## load \"GSS\" data.frame into memory\nbase::load(\"data/chap07/gss2018.rda\")\n\ngss_2018 <- GSS\nsave_data_file(\"chap07\", gss_2018, \"gss_2018.rds\")\n```\n:::\n\n\n(*For this R code chunk is no output available*)\n::::\n:::::\n\n\n### Show raw data {#sec-chap07-show-data}\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap07-show-gss-2018-data}\n: Show summary for some `gss_2018` data\n::::::\n:::\n::::{.my-r-code-container}\n\n::: {.cell}\n\n```{.r .cell-code}\ngss_2018 <- base::readRDS(\"data/chap07/gss_2018.rds\")\ngss_2018 |> \n    dplyr::select(c(\"USETECH\", \"HAPPY\", \"SEX\", \"AGE\", \"DEGREE\")) |> \n    base::summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>     USETECH           HAPPY            SEX             AGE       \n#>  Min.   : -1.00   Min.   :1.000   Min.   :1.000   Min.   :18.00  \n#>  1st Qu.: -1.00   1st Qu.:1.000   1st Qu.:1.000   1st Qu.:34.00  \n#>  Median : 10.00   Median :2.000   Median :2.000   Median :48.00  \n#>  Mean   : 48.09   Mean   :1.855   Mean   :1.552   Mean   :49.13  \n#>  3rd Qu.: 80.00   3rd Qu.:2.000   3rd Qu.:2.000   3rd Qu.:63.00  \n#>  Max.   :999.00   Max.   :8.000   Max.   :2.000   Max.   :99.00  \n#>      DEGREE     \n#>  Min.   :0.000  \n#>  1st Qu.:1.000  \n#>  Median :1.000  \n#>  Mean   :1.684  \n#>  3rd Qu.:3.000  \n#>  Max.   :4.000\n```\n\n\n:::\n:::\n\n***\n\n- **USETECH**: During a typical week, about what percentage of your total time at work would you normally spend using different types of electronic technologies (such as computers, tablets, smart phones, cash registers, scanners, GPS devices, robotic devices, and so on)?\n- **HAPPY**: Taken all together, how would you say things are these days -- would you say that you are very happy, pretty happy, or not too happy?\n- **SEX**: Respondent’s sex\n- **AGE**: Respondent’s age\n- **DEGREE**: Respondent’s highest degree\n- \n::::\n:::::\n\n:::::{.my-procedure}\n:::{.my-procedure-header}\n:::::: {#prp-chap07-gss-procedure}\n: To get the full information for a variable in GSS\n::::::\n:::\n::::{.my-procedure-container}\n1. Go to <https://gssdataexplorer.norc.org/>\n2. In the box \"Access and Analyze GSS Data\" click on the \"SEARCH VARIABLES\" button.\n3. Click at \"Select specific years\", choose \"2018\" and confirm by pressing the \"Apply\"-button.\n4. Input the name of the variable \"USETECH\" into the field and confirm with <enter>.\n5. Open \"Associated questions\" by clicking the `>` symbol or by pressing the \"Show Expanded View\"-button.\n6. Click on the green variable name in the result list to get more detailed information about the variable.\n7. In contrast to the result in the book we get a slightly different coding scheme: We got four (not three) values outside the logical range of 0 to 100: -97, -98, -99, -100.\n\n![Screenshot of GSS Data Explorer 2018 USETECH variable values outside logical range](img/chap07/gss-usetech-codes-min.png){#fig-gss-usetech-codebook\nfig-alt=\"Table of the first 10 lines of GSS Data Explorer 2018 USETECH variable values\"\nfig-align=\"center\"}\n\n::::\n:::::\n\n:::::{.my-important}\n:::{.my-important-header}\nRecoding data exactly as in the book\n:::\n::::{.my-important-container}\nAs we are going to use the data set from the book and not the current data set as it is today (2024-03-25) saved at the GSS website, we will for instance USETECH recode -1, 998 and 999 as missing data in our data frame (and not the current values).  \n\nGenerally: There is nothing new for me in recoding the data. So I will apply all the necessary recoding in the next subsection in only one R code chunk.\n::::\n:::::\n\n\n\n### Recode data {#sec-chap07-recode-data}\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap07-recode-gss2018}\n: Clean `gss_2018` data\n::::::\n:::\n::::{.my-r-code-container}\n\n::: {.cell}\n\n```{.r .cell-code}\n## run only once (manually) ############\ngss_2018 <- base::readRDS(\"data/chap07/gss_2018.rds\")\n\ngss_2018_clean <- gss_2018 |> \n    dplyr::select(c(\"USETECH\", \"HAPPY\", \"SEX\", \"AGE\", \"DEGREE\")) |> \n    dplyr::mutate(USETECH = dplyr::na_if(x = USETECH, y = -1)) |> \n    dplyr::mutate(USETECH = dplyr::na_if(x = USETECH, y = 998)) |>\n    dplyr::mutate(USETECH = dplyr::na_if(x = USETECH, y = 999)) |>\n    dplyr::mutate(AGE = dplyr::na_if(x = AGE, y = 98)) |>\n    dplyr::mutate(AGE = dplyr::na_if(x = AGE, y = 99)) |>\n    dplyr::mutate(DEGREE = dplyr::na_if(x = DEGREE, y = 8)) |>\n    dplyr::mutate(DEGREE = dplyr::na_if(x = DEGREE, y = 9)) |>\n    dplyr::mutate(HAPPY = dplyr::na_if(x = HAPPY, y = 8)) |>\n    dplyr::mutate(HAPPY = dplyr::na_if(x = HAPPY, y = 9)) |>\n    dplyr::mutate(HAPPY = dplyr::na_if(x = HAPPY, y = 0)) |> \n    \n    dplyr::mutate(SEX = forcats::as_factor(SEX)) |> \n    dplyr::mutate(DEGREE = forcats::as_factor(DEGREE)) |> \n    dplyr::mutate(HAPPY = forcats::as_factor(HAPPY)) |> \n    \n    dplyr::mutate(SEX = forcats::fct_recode(SEX, \n                                            male = \"1\", \n                                            female = \"2\")) |> \n    dplyr::mutate(DEGREE = forcats::fct_recode(DEGREE, \n                                            \"< high school\" = \"0\", \n                                            \"high school\" = \"1\",\n                                            \"junior college\" = \"2\",\n                                            \"bachelor\" = \"3\",\n                                            \"graduate\" = \"4\")) |> \n    dplyr::mutate(HAPPY = forcats::fct_recode(HAPPY, \n                                        \"very happy\" = \"1\",\n                                        \"pretty happy\" = \"2\",\n                                        \"not too happy\" = \"3\"))\n\nsave_data_file(\"chap07\", gss_2018_clean, \"gss_2018_clean.rds\")\n\nbase::summary(gss_2018_clean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>     USETECH                 HAPPY          SEX            AGE       \n#>  Min.   :  0.00   very happy   : 701   male  :1051   Min.   :18.00  \n#>  1st Qu.: 15.00   pretty happy :1304   female:1294   1st Qu.:34.00  \n#>  Median : 60.00   not too happy: 336                 Median :48.00  \n#>  Mean   : 55.15   NA's         :   4                 Mean   :48.98  \n#>  3rd Qu.: 90.00                                      3rd Qu.:63.00  \n#>  Max.   :100.00                                      Max.   :89.00  \n#>  NA's   :936                                         NA's   :7      \n#>             DEGREE    \n#>  < high school : 262  \n#>  high school   :1175  \n#>  junior college: 196  \n#>  bachelor      : 465  \n#>  graduate      : 247  \n#>                       \n#> \n```\n\n\n:::\n:::\n\n\n::::\n:::::\n\n\n\n## Achievement 1: Descriptive statistics {#sec-chap07-achievement1}\n\nThe work in this section is done in @sec-chap07-get-data, @sec-chap07-show-data and @sec-chap07-recode-data.\n\n### Explorative Data Analysis (EDA)\n\n**Question to explore**: Do people with higher educational degrees use technology at work more than people with lower degree?\n\n:::::{.my-example}\n:::{.my-example-header}\n:::::: {#exm-chap07-eda}\n: Explorative Data Analysis (EDA)\n::::::\n:::\n::::{.my-example-container}\n\n::: {.panel-tabset}\n\n###### mean / sd\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap07-usetech-mean-sd}\n: Mean and standard deviation of technology use by respondent’s highest degree\n::::::\n:::\n::::{.my-r-code-container}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngss_2018_clean <- base::readRDS(\"data/chap07/gss_2018_clean.rds\")\n\nusetech_degree <- gss_2018_clean |> \n    tidyr::drop_na(USETECH, DEGREE) |>\n    dplyr::group_by(DEGREE) |> \n    dplyr::summarize(mean_usetech = mean(USETECH),\n                     sd_usetech = sd(USETECH))\nusetech_degree\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 5 × 3\n#>   DEGREE         mean_usetech sd_usetech\n#>   <fct>                 <dbl>      <dbl>\n#> 1 < high school          24.8       36.2\n#> 2 high school            49.6       38.6\n#> 3 junior college         62.4       35.2\n#> 4 bachelor               67.9       32.1\n#> 5 graduate               68.7       30.2\n```\n\n\n:::\n:::\n\n***\nIt seems that we could affirm our question. With higher degree the value of the mean (representing the percentage of technology usage) is rising. But we have a big standard deviation, especially in the lowest degree group ($sd \\approx 1.5 mean$). This could indicate that we have not a normal distribution because of high <a class='glossary' title='Kurtosis is a measure of how many observations are in the tails of a distribution; distributions that look bell-shaped, but have a lot of observations in the tails (platykurtic) or very few observations in the tails (leptokurtic) (SwR, Glossary)'>kurtosis</a>, e.g. we could have more observations in the tails than a normal distribution would have (<a class='glossary' title='Platykurtic is a distribution of a numeric variable that has more observations in the tails than a normal distribution would have; platykurtic distributions often look flatter than a normal distribution. (SwR, Glossary)'>platykurtic</a>).\n\n::::\n:::::\n\n\n###### replicate Figure 7.4\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap07-replicate-7-4}\n: Distribution of work time spent using technology by educational attainment\n::::::\n:::\n::::{.my-r-code-container}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngg_gss_2018 <- gss_2018_clean |> \n  tidyr::drop_na(USETECH) |> \n  ggplot2::ggplot(\n      ggplot2::aes(\n          x = DEGREE,\n          y = USETECH\n          )\n      ) +\n  ggplot2::geom_jitter(\n      ggplot2::aes(color = DEGREE), alpha = .6\n      ) +\n  ggplot2::geom_boxplot(\n      ggplot2::aes(fill = DEGREE), alpha = .4\n      ) +\n  ggplot2::scale_fill_brewer(\n      palette = \"Spectral\", \n      guide = \"none\"\n      ) +\n  ggplot2::scale_color_brewer(\n      palette = \"Spectral\", \n      guide = \"none\") +\n  ggplot2::theme_bw() +\n  ggplot2::labs(\n      x = \"Highest educational attainment\", \n      y = \"Percent of time spent using technology\"\n      )\n\ngg_gss_2018\n```\n\n::: {.cell-output-display}\n![Distribution of work time spent using technology by educational attainment, using palette 'Spectral' of brewer scales](07-analysis-of-variance_files/figure-html/fig-replicate-7-4-1.png){#fig-replicate-7-4 width=672}\n:::\n:::\n\n***\n\nHarris uses with this graph (Figure 7.4 in her book) the color schemes from [ColorBrewer](https://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3). See for more details the [color palettes of RColorBrewer](https://renenyffenegger.ch/notes/development/languages/R/packages/RColorBrewer/index) and the [screenshot](https://renenyffenegger.ch/notes/development/languages/R/packages/tmaptools/index#r-tmaptools-palette_explorer) of the `tmaptools::palette_explorer()` function. \n\nBut the chosen color palette is not appropriate for people with color vision deficiency (<a class='glossary' title='Color vision deficiency (CVD) or color blindness (also spelled colour blindness) includes a wide range of causes and conditions and is actually quite complex. It’s a condition characterized by an inability or difficulty in perceiving and differentiating certain colors due to abnormalities in the three color-sensing pigments of the cones in the retina. (EnChroma)'>CVD</a>). Mainly the yellow color is problematic as can be demonstrated with the following plot:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolorblindr::cvd_grid(gg_gss_2018)\n```\n\n::: {.cell-output-display}\n![](07-analysis-of-variance_files/figure-html/fig-check-colorblind-save-gss_2018-plot-1.png){#fig-check-colorblind-save-gss_2018-plot width=672}\n:::\n:::\n\n\n\n::::\n:::::\n\n###### better colors\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap07-techuse-dist}\n: Distribution of work time spent using technology by educational attainment (colorblind save)\n::::::\n:::\n::::{.my-r-code-container}\n\n::: {.cell}\n\n```{.r .cell-code}\ngg2_gss_2018 <- gss_2018_clean |> \n  tidyr::drop_na(USETECH) |> \n  ggplot2::ggplot(\n      ggplot2::aes(\n          x = DEGREE,\n          y = USETECH\n          )\n      ) +\n  ggplot2::geom_jitter(\n      ggplot2::aes(color = DEGREE), alpha = .6\n      ) +\n  ggplot2::geom_boxplot(\n      ggplot2::aes(fill = DEGREE), alpha = .4\n      ) + \n  ggokabeito::scale_color_okabe_ito(guide = \"none\") +\n  ggokabeito::scale_fill_okabe_ito(guide = \"none\") +\n  ggplot2::theme_bw() +\n  ggplot2::labs(\n      x = \"Highest educational attainment\", \n      y = \"Percent of time spent using technology\"\n  )\n\ngg2_gss_2018\n```\n\n::: {.cell-output-display}\n![Distribution of work time spent using technology by educational attainment, using the color save palette 'Okabe-Ito'](07-analysis-of-variance_files/figure-html/techuse-dist-1.png){width=672}\n:::\n\n```{.r .cell-code}\ncolorblindr::cvd_grid(gg2_gss_2018)\n```\n\n::: {.cell-output-display}\n![Distribution of work time spent using technology by educational attainment, using the color save palette 'Okabe-Ito'](07-analysis-of-variance_files/figure-html/techuse-dist-2.png){width=672}\n:::\n:::\n\n\n***\n\nAlthough the color palette \"Okabe-Ito\" is also using a kind of yellow the result is much better in all CVD variants. Compare it with @fig-check-colorblind-save-gss_2018-plot.\n::::\n:::::\n\n\n:::\n\n::::\n:::::\n\nWhat we can see with the graph is that there are many observation at the bottom and at the top of the range of the variable `USETECH`.  \n\n- Many people in the first two categories had selected 0% of their time at work is spent using technology (<a class='glossary' title='A floor effect happens when a variable has many observations that take the lowest value of the variable, which can indicate that the range of values was insufficient to capture the true variability of the data. (SwR, Glossary)'>Floor effect</a>).\n- For all but the first category, there were a lot of people who selected 100% of their time at work is spent using technology (<a class='glossary' title='A ceiling effect happens when many observations are at the highest possible value for a variable. (SwR, Glossary)'>Ceiling effect</a>).\n\n:::::{.my-watch-out}\n:::{.my-watch-out-header}\nWATCH OUT! ANOVA with floor and ceiling effect\n:::\n::::{.my-watch-out-container}\n\nWhen there are floor or ceiling effects, this often means that the variation in a measure is limited by its range. Since ANOVA is an analysis of variance, which examines central tendency and variation together, the limitations of floor and ceiling effects can result in not finding differences when there are differences.\n\nSometimes floor or ceiling effects are hints that the range of the variable is not chosen correctly. But this does not apply in our case, because the range of using technology from 0 to 100% is as wide as it can be. Besides I believe these extreme values do not relate to the true value of technology use in work. I think that today there is almost no work without some sort of technology support. On the other hand it is no very likely that 100% (every second of work) of technology use is realistic.\n::::\n:::::\n\n## Achievement 2: Conducting one-way ANOVA {#sec-chap07-achievement2}\n\n### Introduction\n\nYou can't apply the <a class='glossary' title='A t-test is a type of statistical analysis used to compare the averages of two groups and determine whether the differences between them are more likely to arise from random chance. (Wikipedia)'>t-test</a> as a number of different pairwise tests to compare categorical variables that have several levels (groups). The problem is that the <a class='glossary' title='Rejecting the null hypothesis when it should be retained is called Type I error or alpha and used as the threshold to determine statistical significance. (SwR, Glossary)'>Type I error</a> piles ab with several tests. For example: With five groups in the `DEGREE` variable, pairwise comparisons with a t-test (i.e., conducting <a class='glossary' title='Pairwise comparisons are comparisons between every pair of groups to identify which are statistically significantly different from one another following a statistically significant result in an analysis of variance (ANOVA) or other multigroup analysis. (SwR, Glossary)'>pairwise comparisons</a>) would result in 10 t-tests. If each t-test had a p-value threshold of .05 for statistical significance, the probability of at least one Type I error is fairly high.\n\n***\n\n::: {#exp-chap07-type-1-2-errors}\n\n- **Type I error**: A glossary(\"Type-1\", \"Type I error\")`, also called $\\alpha$, is when there is no relationship but the study detects one. The $\\alpha$ for Type I error is also the threshold set for statistical significance. The threshold for statistical significance is the amount of uncertainty tolerated in concluding whether or not a result is statistically significant.\n- **Type II error**: A <a class='glossary' title='Retaining the null hypothesis when it should be rejected is calles Type II error or beta. (SwR, Glossary)'>Type II error</a>, also called $\\beta$, occurs when there is a relationship but the study did not detect it.\n- **Statistical power**: The power of a statistical test is the probability that the results of the test are not a Type II error.\n\nDefinition of Type I and Type II errors\n:::\n***\n\n\n:::::{.my-theorem}\n:::{.my-theorem-header}\n:::::: {#thm-chap07-familywise-type-1}\n: Probability of a Type I error when there are multiple comparisons\n::::::\n:::\n::::{.my-theorem-container}\n$$\n\\begin{align*}\n\\alpha_{f} = 1 - (1 - \\alpha_{i})^c \\\\\nc = \\frac{k(k-1)}{2}\n\\end{align*}\n$$ {#eq-chap07-familywise-type-1}\n\n***\n\n- $\\alpha_{f}$: <a class='glossary' title='Familywise error is the alpha or Type I error rate when conducting multiple statistical tests. A large familywise alpha is one of the reasons that analysis of variance is preferable to conducting multiple t-tests when comparing means across more than two groups. (SwR, Glossary)'>familywise</a> Type I error rate\n- $\\alpha_{i}$: the individual alpha set as the statistical significance threshold\n- $c$: number of comparisons\n- $k$: total number of groups\n\n***\n\nFor a five-group `DEGREE` variable with $\\alpha = .05$ for each pairwise comparison the familywise $\\alpha_{f}$ would be:\n\n$$\n\\begin{align*}\n\\alpha_{f} = 1-(1-0.05_{i})^\\frac{5(5-1)}{2} = \\\\\n\\alpha_{f} = 1-(1-0.05_{i})^{10} = 0.4012631\n\\end{align*}\n$$\n\n::::\n:::::\n\n> With 10 pairwise comparisons, the familywise $\\alpha_{f}$ indicated there would be a 40% probability of making a Type I error. To control this error rate, and for efficiency, use a single ANOVA test instead of 10 t-tests. ANOVA is useful for testing whether three or more means are equal. It can be used with two means, but the t-test is preferable because it is more straightforward.\n\n:::::{.my-note}\n:::{.my-note-header}\nRunning many tests\n:::\n::::{.my-note-container}\nI believe that the problem of a rising Type I error with a growing number of pairwise comparisons is also valid for other type of tests. Each test has the .05 threshold and a collection of many different tests with the same data rises the probability of making a Type I error. Using this strategy consciously is one form of <a class='glossary' title='P-hacking is a set of statistical decisions and methodology choices during research that artificially produces statistically significant results. These decisions increase the probability of false positives—where the study indicates an effect exists when it actually does not. P-hacking is also known as data dredging, data fishing, and data snooping. (Statistics by Jim)'>p-hacking</a>.\n::::\n:::::\n\n\n### F-Test statistic for ANOVA\n\nThe F-statistic is a ratio where the variation between the groups is compared to the variation within the groups. The between-group variation is in the numerator to calculate F, while the within-group variation is in the denominator.\n\n> Subtracting the grand mean from the group mean results in the difference between the group and the overall sample. The difference between the grand mean and the group mean can be positive or negative and so is squared for the sum to more accurately represent the total of the differences. This squared value is then multiplied by nj or the number of people in the group and divided by k – 1, where k is the number of groups. This results in a numerator that quantifies the difference between the group means and grand mean for all the participants in the sample.\n\n> The denominator sums the squared difference between each individual observation yij and the mean of the individual’s group, quantifying how far the individuals in the group are from the mean of the group. This is divided by the number of individuals in the whole sample minus the number of groups.\n\n\n:::::{.my-theorem}\n:::{.my-theorem-header}\n:::::: {#thm-chap07-f-statistic}\n: F-Statistic\n::::::\n:::\n::::{.my-theorem-container}\n\n$$\n\\begin{align*}\nF &= \\frac{\\text{between-group variability}}{\\text{within-group variability}} \\\\\n&= \\frac{\\text{explained variance}}{\\text{unexplained variance}} \\\\\n&= \\frac{s_{between}^2}{s_{within}^2}\n\\end{align*}\n$$ {#eq-chap07-f-statistic}\n\n***\n\n> The F-statistic, then, could be referred to as a ratio of explained to unexplained variance. That is, how much of the variability in the outcome does the model explain compared to how much it leaves unexplained? The larger the F-statistic, the more the model has explained compared to what it has left unexplained.\n\n> The F-statistic can also be represented as the ratio of the variance between the groups to the variance within the groups.\n\n::::\n:::::\n\n### Computing F-test for using technology at the work place\n\n:::::{.my-example}\n:::{.my-example-header}\n:::::: {#exm-chap07-f-test}\n: F-test for using technology at the work place\n::::::\n:::\n::::{.my-example-container}\n\n::: {.panel-tabset}\n\n###### F-test\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap07-f-test-usetech-degree}\n: Applying F-test `stats::oneway.test()`\n::::::\n:::\n::::{.my-r-code-container}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngss_2018_clean <- base::readRDS(\"data/chap07/gss_2018_clean.rds\")\n\nstats::oneway.test(\n    formula = USETECH ~ DEGREE,\n    data = gss_2018_clean,\n    var.equal = TRUE\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tOne-way analysis of means\n#> \n#> data:  USETECH and DEGREE\n#> F = 43.304, num df = 4, denom df = 1404, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\n::::\n:::::\n\n\n###### grand & group means\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap07-replicate-figure7-5}\n: Distribution of work time spent using technology by educational attainment, with grand mean and group means (Replication of book Figure 7.5)\n::::::\n:::\n::::{.my-r-code-container}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrand_mean <- \n    base::mean(gss_2018_clean$USETECH, na.rm = TRUE)\n\ngroup_means <- gss_2018_clean |> \n    tidyr::drop_na(USETECH, DEGREE) |> \n    dplyr::group_by(DEGREE) |> \n    dplyr::summarize(mean = mean(USETECH))\n\ngg3_gss_2018 <- gss_2018_clean |> \n  tidyr::drop_na(USETECH) |> \n  ggplot2::ggplot(\n      ggplot2::aes(\n          x = DEGREE,\n          y = USETECH\n          )\n      ) +\n  ggplot2::geom_jitter(\n      ggplot2::aes(\n          alpha = .6\n      ),\n      color = \"darkgrey\"\n  ) +\n  ggplot2::geom_hline(\n      ggplot2::aes(\n          yintercept = grand_mean,\n          linetype = \"solid\"\n      ),\n      color = \"steelblue\",\n      linewidth = 1\n  ) +\n  ggplot2::geom_point(\n      data = group_means,\n      ggplot2::aes(\n          x = DEGREE,\n          y = mean,\n          size = 3\n      ),\n      color = \"purple4\",\n      inherit.aes = FALSE\n  ) +\n  ggplot2::theme_bw() +\n  ggplot2::labs(\n      x = \"Highest educational attainment\", \n      y = \"Percent of time spent using technology\"\n  ) +\n  ggplot2::scale_size_continuous(\n      name = \"\",\n      labels = \"Group mean\"\n  ) +\n  ggplot2::scale_linetype_discrete(\n      name = \"\",\n      labels = \"Grand mean\"\n  ) +\n  ggplot2::scale_alpha_continuous(\n      name = \"\",\n      labels = \"Observation\"\n  )\n\ngg3_gss_2018\n```\n\n::: {.cell-output-display}\n![Distribution of work time spent using technology by educational attainment, with grand mean and group means](07-analysis-of-variance_files/figure-html/techuse-dist-grand-mean-1.png){width=672}\n:::\n:::\n\n\n***\nThis R-Code junk replicates book’s Figure 7.5, which has no accompanying R code.\n\n> For each group, the group mean does a better job than the <a class='glossary' title='Grand mean is the overall mean of a continuous variable that is used to determine distances from the mean for individuals and groups in ANOVA. (SwR, Glossary)'>overall mean</a> of explaining tech use *for that group*. The difference between the group mean and the overall mean is *how much better* the group mean is at representing the data in the group. This difference is used to compute the numerator of the <a class='glossary' title='F-statistic is a test statistic comparing explained and unexplained variance in [ANOVA] and linear regression. The F-statistic is a ratio where the variation between the groups is compared to the variation within the groups. (SwR, Glossary)'>F-statistic</a>.\n::::\n:::::\n\n###### F-distributions\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap07-f-dist-examples}\n: F-distribution examples\n::::::\n:::\n::::{.my-r-code-container}\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot2::ggplot(\n    tibble::tibble(x = c(0, 5)), \n    ggplot2::aes(x = x,\n                 color = \"text\")\n    ) +\n    ggplot2::stat_function(fun = df, \n                           args = list(df1 = 4, df2 = 2000), \n                           ggplot2::aes(color = \"4, 2000\"),\n                           linewidth = .7) +\n    ggplot2::stat_function(fun = df, \n                           args = list(df1 = 4, df2 = 25), \n                           ggplot2::aes(color = \"4, 25\"),\n                           linewidth = .7) +\n    ggplot2::stat_function(fun = df, \n                           args = list(df1 = 2, df2 = 2000), \n                           ggplot2::aes(color = \"2, 2000\"),\n                           linewidth = .7) +\n    ggplot2::stat_function(fun = df, \n                           args = list(df1 = 2, df2 = 25), \n                           ggplot2::aes(color = \"2, 25\"),\n                           linewidth = .7) +\n    ggplot2::scale_color_manual(\n        name = \"Degress of freedom\\n(num, denom)\",\n        values = c(\"purple4\", \"purple\", \"green\", \"seagreen\"),\n        breaks = c(\"4, 2000\",\"4, 25\",\"2, 2000\", \"2, 25\")\n    )\n```\n\n::: {.cell-output-display}\n![F-distribution examples](07-analysis-of-variance_files/figure-html/fig-f-dist-examples-1.png){#fig-f-dist-examples width=672}\n:::\n:::\n\n\n::::\n:::::\n\n###### Technology use (ANOVA)\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap07-f-statistic-tech-use}\n: F-distribution for the technology use by degree ANOVA (df = 4 and 1404)\n::::::\n:::\n::::{.my-r-code-container}\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot2::ggplot(\n    tibble::tibble(x = c(0, 5)), \n    ggplot2::aes(x = x)\n    ) +\n    ggplot2::stat_function(fun = df, \n                           args = list(df1 = 4, df2 = 1404), \n                           linewidth = .7)\n```\n\n::: {.cell-output-display}\n![F-distribution for the technology use by degree ANOVA (df = 4 and 1404)](07-analysis-of-variance_files/figure-html/fig-f-statistic-tech-use-1.png){#fig-f-statistic-tech-use width=672}\n:::\n:::\n\n***\n\n> The F-distribution in @fig-f-statistic-tech-use suggested the F-statistic of 43.30 was far to the right in the tail of the distribution. The probability of an F-statistic this large or larger if the null were true was reported in the output as < 2.2e-16, which is < .001. With a p-value this tiny, the F-statistic would be considered statistically significant.\n\n\n\n::::\n:::::\n\n\n:::\n\n::::\n:::::\n\n::: {.callout-tip}\n> The mean time spent on technology use was significantly different across degree groups [F(4, 1404) = 43.3; p < .05], indicating that these groups likely came from a population with different mean time spent on technology use by educational attainment. The highest mean was the percent of time used for technology by those with graduate degrees. The lowest mean was the percent of time used for technology by those with less than a high school diploma.\n:::\n\n\n## Achievement 3: Post hoc tests & contrasts {#sec-chap07-achievement3}\n\n<a class='glossary' title='Analysis of variance is a statistical method used to compare means across groups to determine whether there is a statistically significant difference among the means; typically used when there are three or more means to compare. (SwR, Glossary)'>ANOVA</a> is --- similar as the <a class='glossary' title='Chi-squared is the test statistic following the chi-squared probability distribution; the chi-squared test statistic is used in inferential tests, including examining the association between two categorical variables and determining statistical significance for a logistic regression model. (SwR, Glossary)'>chi-squared test</a> --- an <a class='glossary' title='An omnibus is a statistical test that identifies that there is some relationship going on between variables, but not what that relationship is. (SwR, Glossary)'>omnibus</a> test: iIt identifies whether there are any differences, but doesn’t give any information about what is driving the significant results.\n\nThere are two main ways to determine where significant differences among groups are following a significant omnibus test:\n\n- **Post hoc tests**: Examining each pair of means to determine which means are the most different from each other.\n- **Planned contrasts**: Comparing specified subsets of means or groups of means.\n\n### Post hoc tests\n\n#### Bonferroni\n\nThere are several different types of post hoc tests, and one of the more commonly used is the <a class='glossary' title='Bonferroni post hoc test is a pairwise test used after a statistically significant ANOVA that conducts a t-test for each pair of means but adjusts the threshold for statistical significance to ensure that there is a small enough risk of Type I error; it is generally considered a very conservative post hoc test that only identifies the largest differences between means as statistically significant. (SwR, Glossary)'>Bonferroni post hoc test</a>.\n\nThe Bonferroni adjustment multiplies each <a class='glossary' title='The p-value is the probability that the test statistic is at least as big as it is under the null hypothesis (SwR, Glossary)'>p-value</a> from each <a class='glossary' title='A t-test is a type of statistical analysis used to compare the averages of two groups and determine whether the differences between them are more likely to arise from random chance. (Wikipedia)'>t-test</a> by the overall number of t-tests conducted. There were 10 pairwise comparisons (5 groups each pairwise = 5 * 2), so these p-values have been multiplied by 10. Higher p-values will not reach the threshold for statistical significance as often. Sometimes there are resulting p-values of 1.0000. As the p-value cannot be over 1, so for p-values that are over 1 when adjusted by the multiplication, they are rounded to exactly 1.0000.\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap07-bonferroni-test}\n: Bonferroni post hoc test\n::::::\n:::\n::::{.my-r-code-container}\n\n::: {.cell}\n\n```{.r .cell-code}\nstats::pairwise.t.test(\n    x = gss_2018_clean$USETECH,\n    g = gss_2018_clean$DEGREE,\n    p.adjust.method = \"bonferroni\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tPairwise comparisons using t tests with pooled SD \n#> \n#> data:  gss_2018_clean$USETECH and gss_2018_clean$DEGREE \n#> \n#>                < high school high school junior college bachelor\n#> high school    3.8e-11       -           -              -       \n#> junior college 2.8e-15       0.0022      -              -       \n#> bachelor       < 2e-16       8.0e-13     1.0000         -       \n#> graduate       < 2e-16       7.3e-09     1.0000         1.0000  \n#> \n#> P value adjustment method: bonferroni\n```\n\n\n:::\n:::\n\n***\n\nThe output is different from previous statistical testing. Instead of a test statistic like t or F, the output is a matrix of p-values.\n\nThe adjusted p-values for seven of the t-tests fall below .05 and so indicate that the difference in mean time using technology between two groups is statistically significant.\n\n- There are significant differences in mean time between less than high school and all of the other groups (p < .05); \n- Likewise, there are significant differences in mean time using technology between high school and all other groups. \n- There are no significant differences among the means of the three college groups (junior college, bachelor, graduate).\n\n\n::::\n:::::\n\nFor the report it would be more informative if one could add the group means for the interpretation:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngss_2018_clean |> \n    tidyr::drop_na(USETECH, DEGREE) |> \n    dplyr::group_by(DEGREE) |> \n    dplyr::summarize(\n        group_means = base::round(base::mean(USETECH), 1)\n    )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 5 × 2\n#>   DEGREE         group_means\n#>   <fct>                <dbl>\n#> 1 < high school         24.8\n#> 2 high school           49.6\n#> 3 junior college        62.4\n#> 4 bachelor              67.9\n#> 5 graduate              68.7\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip}\n> Mean percentage of time using technology at work was statistically significantly (p < .05) lower for people with less educational attainment than a high school diploma (m = 24.8) compared to each of the other groups, where the mean percentage of time using technology ranged from 49.6 to 68.7.\n:::\n\n#### Tukey’s Honestly Significance Difference (HSD)\n\nTukey’s HSD post hoc test is a modified <a class='glossary' title='A t-test is a type of statistical analysis used to compare the averages of two groups and determine whether the differences between them are more likely to arise from random chance. (Wikipedia)'>t-test</a> with the test statistic, `q`. The `q` test statistic formula is the same as some versions of `t`, but the q-distribution is different from the t-distribution, raising the critical value necessary to reach statistical significance. Even with the same test statistic, it is more difficult to reach statistical significance with a Tukey’s <a class='glossary' title='Tukey’s Honestly Significant Difference (HSD) is a post hoc test to determine which means are statistically significantly different from each other following a significant ANOVA result; Tukey’s HSD compares each pair of means and so is considered a pairwise test, but it is less conservative than the Bonferroni post hoc test. (SwR, Glossary)'>HSD</a> q-statistic compared to a t-test.\n\n$$\nq = \\frac{m_{1} - m_{2}}{se}\n$$ {#eq-chap07-hsd}\n\nThe `stats::TukeyHSD()` function does not work well with the `stats::oneway.test()` output from earlier, so the entire ANOVA model has to be re-estimated. The `stats:aov()` function works and takes similar arguments to the `stats::oneway.test()` function, so nesting the `stats::aov()` inside the `stats::TukeyHSD()` is one way to go.\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap07-hsd}\n: Compute Tukey’s Honestly Significance Difference (HSD)\n::::::\n:::\n::::{.my-r-code-container}\n\n::: {.cell}\n\n```{.r .cell-code}\nstats::TukeyHSD(\n    stats::aov(\n    formula = USETECH ~ DEGREE,\n    data = gss_2018_clean\n    )\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>   Tukey multiple comparisons of means\n#>     95% family-wise confidence level\n#> \n#> Fit: stats::aov(formula = USETECH ~ DEGREE, data = gss_2018_clean)\n#> \n#> $DEGREE\n#>                                    diff       lwr      upr     p adj\n#> high school-< high school    24.8247754 15.145211 34.50434 0.0000000\n#> junior college-< high school 37.6070313 25.201887 50.01218 0.0000000\n#> bachelor-< high school       43.0859568 32.653180 53.51873 0.0000000\n#> graduate-< high school       43.9107249 32.256416 55.56503 0.0000000\n#> junior college-high school   12.7822558  3.362603 22.20191 0.0020352\n#> bachelor-high school         18.2611813 11.651711 24.87065 0.0000000\n#> graduate-high school         19.0859494 10.679691 27.49221 0.0000000\n#> bachelor-junior college       5.4789255 -4.713166 15.67102 0.5833665\n#> graduate-junior college       6.3036936 -5.135659 17.74305 0.5592907\n#> graduate-bachelor             0.8247681 -8.438819 10.08835 0.9992282\n```\n\n\n:::\n:::\n\n\nThe number of significant results of the 10 test are the same, although the Bonferroni test is more conservative. For example the p-value of the pairwise test between junior college and bachelor are 0.58 in HSD but 1.0 in Bonferroni.\n\n::::\n:::::\n\n::: {.callout-tip}\nThe mean time spent on technology use was significantly different across education groups [F(4, 1404) = 43.3; p < .05], indicating that these groups likely came from a population with different mean time spent on technology use depending on educational attainment. The highest mean was 68.7% of time used for technology for those with graduate degrees. The lowest mean was 24.8% of the time for those with less than a high school diploma. Mean percentage of time using technology was statistically significantly (p < .05) *lower* for people with less than a high school diploma (m = 24.8) compared to each of the other groups where the mean percentage of time using technology ranged from 49.6 to 68.7.\n:::\n\n\n### Planned comparisons\n\n#### Introduction\n\n<a class='glossary' title='Planned comparisons is a statistical strategy for comparing different groups, often used after a statistically significant analysis of variance to test hypotheses about which group means are statistically significantly different from one another. (SwR, Glossary)'>Planned comparisons</a> are computed by developing <a class='glossary' title='Contrasts are sets of numbers used in planned contrasts to specify which means or groups of means to compare to each other, usually to identify statistically significant differences among means after a statistically significant analysis of variance. (SwR, Glossary)'>contrasts</a> that specify which means to compare to which other means.\n\n::: {#bul-planned-contrasts}\n\n- The order of the factor variable is the exact order that should be used in the contrast.\n- A contrast is a group of numbers used to group categories. \n- The categories grouped together should all be represented by the same number in the contrast. \n- The numbers in the contrast should all add to zero. \n- Any category not included in the contrast should be represented by a zero.\n\nRules for planned contrasts \n:::\n\nFor example, to compare all the college groups to the high school group, the contrast would omit the less than high school group and compare the mean for everyone in the high school group to the mean of the combined three college groups: junior college, bachelor, and graduate.\n\n- 0 (< high school: do not include) \n- 3 (high school) \n- –1 (junior college) \n- –1 (bachelor) \n- –1 (graduate)\n\nThe three categories represented by –1 will be grouped together because they are all represented by the same number.\n\n#### Compute planned contrasts\n\n:::::{.my-example}\n:::{.my-example-header}\n:::::: {#exm-chap07-planned-constrasts}\n: Planned contrasts of using technology by degree\n::::::\n:::\n::::{.my-example-container}\n\n\n::: {.panel-tabset}\n\n###### high school & colleges\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap07-contrast-high-school-colleges}\n: Planned contrasts of using technology for the college groups to high school group\n::::::\n:::\n::::{.my-r-code-container}\n\n::: {.cell}\n\n```{.r .cell-code}\n## 1. put the contrast into a vector\ncontrast1 <- c(0, 3, -1, -1, -1)\n\n## 2. link the contrast to the categorical variable using contrasts()\nstats::contrasts(x = gss_2018_clean$DEGREE) <- contrast1\n\n## 2a. view the structure of the DEGREE variable with contrast\nglue::glue(\"************** View the structure of DEGREE variable *****************\")\nutils::str(object = gss_2018_clean$DEGREE)\n\n## 3. re-run the model using aov()\nusetech_degree_aov <- stats::aov(\n    formula = USETECH ~ DEGREE,\n    data = gss_2018_clean\n)\n\n## 4. apply the contrasts to the aov object\nglue::glue(\" \")\nglue::glue(\"******************* Summarize the aov object ****************************\")\nstats::summary.aov(\n    object = usetech_degree_aov,\n    split = list(DEGREE = \n            list(\"high school vs. all college\" = 1)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> ************** View the structure of DEGREE variable *****************\n#>  Factor w/ 5 levels \"< high school\",..: 3 2 4 4 5 4 2 2 1 2 ...\n#>  - attr(*, \"contrasts\")= num [1:5, 1:4] 0 3 -1 -1 -1 ...\n#>   ..- attr(*, \"dimnames\")=List of 2\n#>   .. ..$ : chr [1:5] \"< high school\" \"high school\" \"junior college\" \"bachelor\" ...\n#>   .. ..$ : NULL\n#>  \n#> ******************* Summarize the aov object ****************************\n#>                                         Df  Sum Sq Mean Sq F value   Pr(>F)    \n#> DEGREE                                   4  221301   55325   43.30  < 2e-16 ***\n#>   DEGREE: high school vs. all college    1   64411   64411   50.41 1.97e-12 ***\n#> Residuals                             1404 1793757    1278                     \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> 936 observations deleted due to missingness\n```\n\n\n:::\n:::\n\n\n***\n\nThe output showed that mean technology use for those who finished high school was statistically significantly different from mean technology use for the three college groups combined [F(1, 1404) = 50.41; p < .001].\n\nTo understand more of what was happening we need to lookat the means being compared with this contrast.\n\n::::\n:::::\n\n\n###### recode high school & colleges\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap07-contrast-no-high-school-colleges}\n: Using technology for the recoded planned contrast between college groups to high school group\n::::::\n:::\n::::{.my-r-code-container}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngss_2018_clean |> \n    dplyr::mutate(DEGREE =\n          forcats::fct_collapse(DEGREE,\n                `all college` = c(\n                    \"junior college\",\n                    \"bachelor\",\n                    \"graduate\"\n                    ) \n                )\n          ) |> \n    dplyr::group_by(DEGREE) |> \n    dplyr::summarize(mean_usetech = mean(USETECH, na.rm = TRUE),\n                     sd_usetech = sd(USETECH, na.rm = TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 3 × 3\n#>   DEGREE        mean_usetech sd_usetech\n#>   <fct>                <dbl>      <dbl>\n#> 1 < high school         24.8       36.2\n#> 2 high school           49.6       38.6\n#> 3 all college           67.0       32.3\n```\n\n\n:::\n:::\n\n***\n\nI have used here the first time the `forcats::fct_collaps()` function. This is more understandable as the option in the book, where (a) all factors are recoded and the thre highest factors with the same name \"all college\".\n\nThe difference between the mean technology use time for high school (m = 49.61) compared to all college groups combined (m = 66.97) is pretty large.\n\n::::\n:::::\n\n###### Plot hs & colleges\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap07-graph-contrast-no-high-school-colleges}\n: Plot of using technology for the recoded planned contrast between college groups to high school group\n::::::\n:::\n::::{.my-r-code-container}\n\n::: {.cell}\n\n```{.r .cell-code}\ngss_2018_clean |> \n    dplyr::mutate(DEGREE =\n          forcats::fct_collapse(DEGREE,\n                `all college` = c(\n                    \"junior college\",\n                    \"bachelor\",\n                    \"graduate\"\n                    ) \n                )\n          ) |> \n    dplyr::filter(DEGREE == \"high school\" | DEGREE == \"all college\") |> \n    \n    ggplot2::ggplot(\n        ggplot2::aes(\n            y = USETECH, \n            x = DEGREE, \n            fill = DEGREE, \n            color = DEGREE\n        )\n    ) +\n    ggplot2::geom_boxplot(\n        alpha = .4,\n        na.rm = TRUE\n        ) + \n    ggplot2::geom_jitter(\n        alpha = .6,\n        na.rm = TRUE\n        ) + \n    ggplot2::scale_fill_manual(\n        values = c(\"gray70\", \"#7463AC\"), \n        guide = \"none\"\n        ) + \n    ggplot2::scale_color_manual(\n        values = c(\"gray70\", \"#7463AC\"), \n        guide = \"none\"\n        ) + \n    ggplot2::labs(\n        x = \"Educational attainment\", \n        y = \"Percent of time spent using technology\"\n        )\n```\n\n::: {.cell-output-display}\n![Contrast between time using technology for the high school group to the three college groups (junior college, beachelor, graduate)](07-analysis-of-variance_files/figure-html/fig-graph-contrast-no-high-school-colleges-1.png){#fig-graph-contrast-no-high-school-colleges width=672}\n:::\n:::\n\n***\nIt is clear that the means of these two groups are different. The same probably would also be true for the less than high school group with the three college groups.\n::::\n:::::\n\n###### < hs to colleges\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap07-contrast-less-hs-colleges}\n: Planned contrasts of time using technology on the job between college groups to less than high school group\n::::::\n:::\n::::{.my-r-code-container}\n\n::: {.cell}\n\n```{.r .cell-code}\n## 1. less than high school v. all college contrast\ncontrast2 <- base::c(3, 0, -1, -1, -1)\n\n## 2. bind the two contrasts together (matrix required!)\nmy_contrasts <- \n    as.matrix(dplyr::bind_cols(\n        contrast1 = contrast1, \n        contrast2 = contrast2))\n\n## 3. connect the tibble with factor variable\nstats::contrasts(gss_2018_clean$DEGREE) <-  my_contrasts\n\n## 4. compute ANOVA with planned contrasts\nstats::summary.aov(\n    object = usetech_degree_aov,\n    split = list(DEGREE = \n            list(\"high school vs. all college\" = 1,\n                 \"< high school vs. all college\" = 2)\n            )\n    )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>                                           Df  Sum Sq Mean Sq F value   Pr(>F)\n#> DEGREE                                     4  221301   55325   43.30  < 2e-16\n#>   DEGREE: high school vs. all college      1   64411   64411   50.41 1.97e-12\n#>   DEGREE: < high school vs. all college    1   20188   20188   15.80 7.39e-05\n#> Residuals                               1404 1793757    1278                 \n#>                                            \n#> DEGREE                                  ***\n#>   DEGREE: high school vs. all college   ***\n#>   DEGREE: < high school vs. all college ***\n#> Residuals                                  \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> 936 observations deleted due to missingness\n```\n\n\n:::\n:::\n\n\n::::\n:::::\n\n###### plot < hs & colleges\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap07-graph-less-than-hs-all-colleges}\n: Plot of using technology for the recoded planned contrast between college groups to less than high school group\n::::::\n:::\n::::{.my-r-code-container}\n\n::: {.cell}\n\n```{.r .cell-code}\ngss_2018_clean |> \n    dplyr::mutate(DEGREE =\n          forcats::fct_collapse(DEGREE,\n                `all college` = c(\n                    \"junior college\",\n                    \"bachelor\",\n                    \"graduate\"\n                    ) \n                )\n          ) |> \n    \n    ggplot2::ggplot(\n        ggplot2::aes(\n            x = DEGREE, \n            y = USETECH, \n            fill = DEGREE, \n            color = DEGREE\n        )\n    ) +\n    ggplot2::geom_boxplot(\n        alpha = .4,\n        na.rm = TRUE\n        ) + \n    ggplot2::geom_jitter(\n        alpha = .6,\n        na.rm = TRUE\n        ) + \n    ggplot2::scale_fill_manual(\n        values = c(\"gray70\", \"#7463AC\", \"dodgerblue\"), \n        guide = \"none\"\n        ) + \n    ggplot2::scale_color_manual(\n        values = c(\"gray70\", \"#7463AC\", \"dodgerblue\"), \n        guide = \"none\"\n        ) + \n    ggplot2::labs(\n        x = \"Educational attainment\", \n        y = \"Percent of time spent using technology\"\n        )\n```\n\n::: {.cell-output-display}\n![Distribution of tech use at work by degree for contrast comparing all college groups combined to each of the other groups](07-analysis-of-variance_files/figure-html/fig-graph-less-than-hs-all-colleges-1.png){#fig-graph-less-than-hs-all-colleges width=672}\n:::\n:::\n\n\n::::\n:::::\n\n###### 4 contrasts\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap07-4-contrasts}\n: Four planned comparisons\n::::::\n:::\n::::{.my-r-code-container}\n\n::: {.cell}\n\n```{.r .cell-code}\n## contrasts for ANOVA of tech time by degree \nc1 <- c(2, -1, -1, 0, 0) \nc2 <- c(0, 3, -1, -1, -1) \nc3 <- c(0, 0, 2, -1, -1) \nc4 <- c(0, 0, 0, -1, 1) \n\n## bind the contrasts into a matrix \nconts <- cbind(c1, c2, c3, c4) \nconts\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>      c1 c2 c3 c4\n#> [1,]  2  0  0  0\n#> [2,] -1  3  0  0\n#> [3,] -1 -1  2  0\n#> [4,]  0 -1 -1 -1\n#> [5,]  0 -1 -1  1\n```\n\n\n:::\n:::\n\n\n***\n\n:::::{.my-procedure}\n:::{.my-procedure-header}\n:::::: {#prp-chap07-check-contrasts}\n: Check the values of the contrasts\n::::::\n:::\n::::{.my-procedure-container}\n1. Add up each contrast to make sure it adds to zero. \n2. Multiply each value in each contrast with the corresponding values in the other contrasts and add up the products; this should also add to zero.\n::::\n:::::\n\n**ad 1**: The vectors are now columns. An example of a check is to sum the column c1: $2 + (-1) + (-1) + 0 + 0 = 0$. Columns c2, c3 and c4 also result to $0$. So the first check conditions was passed.\n\n**ad 2**: Now we have to multiply the values row-wise: $2 \\times 0 \\times 0 \\times 0 = 0$ It is easy to check: Whenever there is $0$ in one of the columns then the result is also $0$. Adding all these products together results in $0 + 0 + 0 + 0 + 0 = 0$, so the second requirement is also met.\n\n::::\n:::::\n\n###### `aov()` 4 contrasts\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap07-aov-4-contrasts}\n: Conncet the matrix with all levels of the factor variable\n::::::\n:::\n::::{.my-r-code-container}\n\n::: {.cell}\n\n```{.r .cell-code}\n## connect the matrix with the factor variable \nstats::contrasts(x = gss_2018_clean$DEGREE) <- conts \n\n## estimate the ANOVA with 4 independent contrasts \nusetech_degree_4_contrasts <- \n    summary.aov(object = usetech_degree_aov, \n        split = list(DEGREE = \n             list(\"< high school vs. high school & jr college\" = 1, \n                  \"high school vs. all college\" = 2, \n                  \"jr college vs. bach or grad degree\" = 3, \n                  \"bachelor’s vs. graduate degree\" = 4)\n             )\n        ) \nusetech_degree_4_contrasts\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>                                                        Df  Sum Sq Mean Sq\n#> DEGREE                                                  4  221301   55325\n#>   DEGREE: < high school vs. high school & jr college    1   64411   64411\n#>   DEGREE: high school vs. all college                   1   20188   20188\n#>   DEGREE: jr college vs. bach or grad degree            1   63902   63902\n#>   DEGREE: bachelor’s vs. graduate degree                1   72800   72800\n#> Residuals                                            1404 1793757    1278\n#>                                                      F value   Pr(>F)    \n#> DEGREE                                                 43.30  < 2e-16 ***\n#>   DEGREE: < high school vs. high school & jr college   50.41 1.97e-12 ***\n#>   DEGREE: high school vs. all college                  15.80 7.39e-05 ***\n#>   DEGREE: jr college vs. bach or grad degree           50.02 2.40e-12 ***\n#>   DEGREE: bachelor’s vs. graduate degree               56.98 7.88e-14 ***\n#> Residuals                                                                \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> 936 observations deleted due to missingness\n```\n\n\n:::\n:::\n\n\n\n::::\n:::::\n\n###### Adjust p-values\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap07-adjust-p-values}\n: Adjust p-values for multiple comparisons\n::::::\n:::\n::::{.my-r-code-container}\n\n::: {.cell}\n\n```{.r .cell-code}\nadj_p_values <- stats::p.adjust(\n    p = usetech_degree_4_contrasts[[1]][[\"Pr(>F)\"]], \n    method = \"bonferroni\"\n    )\nadj_p_values\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>                                            \n#>                               1.329994e-33 \n#> < high school vs. high school & jr college \n#>                               9.850341e-12 \n#>                high school vs. all college \n#>                               3.696043e-04 \n#>         jr college vs. bach or grad degree \n#>                               1.198280e-11 \n#>             bachelor’s vs. graduate degree \n#>                               3.939123e-13 \n#>                                            \n#>                                         NA\n```\n\n\n:::\n:::\n\n***\n\nThe adjusted p-values were still very small, so the conclusions about statistical significance did not change, even when using a conservative adjustment like <a class='glossary' title='Bonferroni post hoc test is a pairwise test used after a statistically significant ANOVA that conducts a t-test for each pair of means but adjusts the threshold for statistical significance to ensure that there is a small enough risk of Type I error; it is generally considered a very conservative post hoc test that only identifies the largest differences between means as statistically significant. (SwR, Glossary)'>Bonferroni</a>.\n\n::::\n:::::\n\n###### Violin plot\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap07-4-planned-comp-violin-plot}\n: Visualizing the distribution of technology use at work by educational attainment for four planned comparisons\n::::::\n:::\n::::{.my-r-code-container}\n\n::: {.cell}\n\n```{.r .cell-code}\n## < high school / hs & jr college ########\ngg_violin1 <- gss_2018_clean |>\n  dplyr::mutate(DEGREE = \n        dplyr::if_else(DEGREE == \"< high school\", \"< high school\",\n        dplyr::if_else(DEGREE %in% c(\"high school\", \n                                     \"junior college\"),\n                                     \"high school & jr college\",\n                                     NA))) |>\n  dplyr::mutate(DEGREE = \n         base::factor(DEGREE, levels = c(\"< high school\",\n                                         \"high school & jr college\"),\n                                         ordered = T)) |>\n  dplyr::filter(DEGREE == \"< high school\" | \n                DEGREE == \"high school & jr college\") |> \n\n      ggplot2::ggplot(\n        ggplot2::aes(\n            y = USETECH, \n            x = DEGREE, \n            fill = DEGREE, \n            color = DEGREE\n        )\n    ) +\n    ggplot2::geom_violin(\n        alpha = .4,\n        na.rm = TRUE\n        ) + \n    ggplot2::geom_jitter(\n        alpha = .6,\n        na.rm = TRUE\n        ) + \n    ggplot2::scale_fill_manual(\n        values = c(\"gray70\", \"#7463AC\"), \n        guide = \"none\"\n        ) + \n    ggplot2::scale_color_manual(\n        values = c(\"gray70\", \"#7463AC\"), \n        guide = \"none\"\n        ) + \n    ggplot2::labs(\n        x = \"Educational attainment\", \n        y = \"Percent of time spent using technology\"\n        )\n    \n    \n## high school & three college groups##########\ngg_violin2 <- gss_2018_clean |> \n    dplyr::mutate(DEGREE =\n          forcats::fct_collapse(DEGREE,\n                `all college` = c(\n                    \"junior college\",\n                    \"bachelor\",\n                    \"graduate\"\n                    ) \n                )\n          ) |> \n    dplyr::filter(DEGREE == \"high school\" | DEGREE == \"all college\") |>\n    ggplot2::ggplot(\n        ggplot2::aes(\n            y = USETECH, \n            x = DEGREE, \n            fill = DEGREE, \n            color = DEGREE\n        )\n    ) +\n    ggplot2::geom_violin(\n        alpha = .4,\n        na.rm = TRUE\n        ) + \n    ggplot2::geom_jitter(\n        alpha = .6,\n        na.rm = TRUE\n        ) + \n    ggplot2::scale_fill_manual(\n        values = c(\"gray70\", \"#7463AC\"), \n        guide = \"none\"\n        ) + \n    ggplot2::scale_color_manual(\n        values = c(\"gray70\", \"#7463AC\"), \n        guide = \"none\"\n        ) + \n    ggplot2::labs(\n        x = \"Educational attainment\", \n        y = \"Percent of time spent using technology\"\n        )\n\n## jr college & bachelor & graduate ##########\ngg_violin3 <- gss_2018_clean |> \n    dplyr::mutate(DEGREE = \n    dplyr::if_else(DEGREE %in% c(\"< high school\", \"high school\"), NA,\n    dplyr::if_else(DEGREE == \"junior college\", \"jr college\",\n    dplyr::if_else(DEGREE %in% c(\"bachelor\", \"graduate\"),\n                                 \"bachelor or graduate\", NA)))) |>\n    dplyr::mutate(DEGREE = \n      base::factor(DEGREE, \n                   levels = c(\"jr college\", \n                              \"bachelor or graduate\", \n                              ordered = T))) |>\n    dplyr::filter(DEGREE == \"jr college\" | DEGREE == \"bachelor or graduate\") |>\n    \n    ggplot2::ggplot(\n        ggplot2::aes(\n            y = USETECH, \n            x = DEGREE, \n            fill = DEGREE, \n            color = DEGREE\n        )\n    ) +\n    ggplot2::geom_violin(\n        alpha = .4,\n        na.rm = TRUE\n        ) + \n    ggplot2::geom_jitter(\n        alpha = .6,\n        na.rm = TRUE\n        ) + \n    ggplot2::scale_fill_manual(\n        values = c(\"gray70\", \"#7463AC\"), \n        guide = \"none\"\n        ) + \n    ggplot2::scale_color_manual(\n        values = c(\"gray70\", \"#7463AC\"), \n        guide = \"none\"\n        ) + \n    ggplot2::labs(\n        x = \"Educational attainment\", \n        y = \"Percent of time spent using technology\"\n        )\n\n## bachelor & graduate ############\ngg_violin4 <- gss_2018_clean |> \n    dplyr::mutate(DEGREE = \n        dplyr::if_else(DEGREE == \"bachelor\", \"bachelor\",\n        dplyr::if_else(DEGREE == \"graduate\", \"graduate\", NA))) |>\n      dplyr::mutate(DEGREE = \n        base::factor(DEGREE, \n                     levels = c(\"bachelor\", \n                                \"graduate\", \n                                ordered = T))) |>\n    dplyr::filter(DEGREE == \"bachelor\" | DEGREE == \"graduate\") |> \n\n    ggplot2::ggplot(\n        ggplot2::aes(\n            y = USETECH, \n            x = DEGREE, \n            fill = DEGREE, \n            color = DEGREE\n        )\n    ) +\n    ggplot2::geom_violin(\n        alpha = .4,\n        na.rm = TRUE\n        ) + \n    ggplot2::geom_jitter(\n        alpha = .6,\n        na.rm = TRUE\n        ) + \n    ggplot2::scale_fill_manual(\n        values = c(\"gray70\", \"#7463AC\"), \n        guide = \"none\"\n        ) + \n    ggplot2::scale_color_manual(\n        values = c(\"gray70\", \"#7463AC\"), \n        guide = \"none\"\n        ) + \n    ggplot2::labs(\n        x = \"Educational attainment\", \n        y = \"Percent of time spent using technology\"\n        )\n\ngridExtra::grid.arrange(\n    gg_violin1, gg_violin2,\n    gg_violin3, gg_violin4,\n    ncol = 2)\n```\n\n::: {.cell-output-display}\n![Visualizing the distribution of technology use at work by educational attainment for four planned comparisons (violin plot)](07-analysis-of-variance_files/figure-html/fig-4-planned-comp-violin-plot-1.png){#fig-4-planned-comp-violin-plot width=672}\n:::\n:::\n\n\n***\nThis is the replication of book’s Figure 7.10.\n::::\n:::::\n\n###### final\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap07-planned-comp-final}\n: Numbered R Code Title\n::::::\n:::\n::::{.my-r-code-container}\n\n::: {.cell}\n\n```{.r .cell-code}\n## contrast 1 statistics ###########\nglue::glue(\" \")\nglue::glue(\"#################### contrast 1 statistics ###################\")\ngss_2018_clean  |> \n  dplyr::mutate(DEGREE = \n        dplyr::if_else(DEGREE == \"< high school\", \"< high school\",\n        dplyr::if_else(DEGREE %in% c(\"high school\", \n                                     \"junior college\"),\n                                     \"high school & jr college\",\n                                     NA))) |>\n  dplyr::mutate(DEGREE = \n         base::factor(DEGREE, levels = c(\"< high school\",\n                                         \"high school & jr college\"),\n                                         ordered = T)) |>\n  dplyr::group_by(DEGREE) |>\n  dplyr::summarise(\n      mean_usetech = base::mean(x = USETECH, na.rm = T),\n      sd_usetech = stats::sd(x = USETECH, na.rm = T))\n\n\n\n## contrast 2 statistics ##############\nglue::glue(\" \")\nglue::glue(\"#################### contrast 2 statistics ###################\")\ngss_2018_clean |>\n  dplyr::mutate(DEGREE = \n         base::factor(DEGREE, labels = c(NA,\n               \"high school\", \"all college\",\n               \"all college\", \"all college\"),\n               ordered = T)) |>\n  dplyr::group_by(DEGREE) |>\n  dplyr::summarise(\n      mean_usetech = mean(x = USETECH, na.rm = T),\n      sd.usetech = sd(x = USETECH, na.rm = T)) \n\n## contrast 3 statistics ##############\nglue::glue(\" \")\nglue::glue(\"#################### contrast 3 statistics ###################\")\ngss_2018_clean |>\n  dplyr::mutate(DEGREE = \n    dplyr::if_else(DEGREE %in% c(\"< high school\", \"high school\"), NA,\n    dplyr::if_else(DEGREE == \"junior college\", \"jr college\",\n    dplyr::if_else(DEGREE %in% c(\"bachelor\", \"graduate\"),\n                                 \"bach or grad degree\", NA)))) |>\n    dplyr::mutate(DEGREE = \n      base::factor(DEGREE, \n                   levels = c(\"jr college\", \n                              \"bach or grad degree\", \n                              ordered = T))) |>\n  dplyr::group_by(DEGREE) |>\n  dplyr::summarise(\n      mean_usetech = mean(x = USETECH, na.rm = T),\n      sd.usetech = sd(x = USETECH, na.rm = T))\n\n# contrast 4 statistics ####################\nglue::glue(\" \")\nglue::glue(\"#################### contrast 4 statistics ###################\")\ngss_2018_clean |>\n  dplyr::mutate(DEGREE = \n    dplyr::if_else(DEGREE == \"bachelor\", \"bachelor\",\n    dplyr::if_else(DEGREE == \"graduate\", \"graduate\", NA))) |>\n  dplyr::mutate(DEGREE = \n    base::factor(DEGREE, \n                 levels = c(\"bachelor\", \n                            \"graduate\", \n                            ordered = T))) |>\n  dplyr::group_by(DEGREE) |>\n  dplyr::summarise(\n     mean_usetech = mean(x = USETECH, na.rm = T),\n     sd_usetech = sd(x = USETECH, na.rm = T))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>  \n#> #################### contrast 1 statistics ###################\n#> # A tibble: 3 × 3\n#>   DEGREE                   mean_usetech sd_usetech\n#>   <ord>                           <dbl>      <dbl>\n#> 1 < high school                    24.8       36.2\n#> 2 high school & jr college         51.7       38.4\n#> 3 <NA>                             68.2       31.4\n#>  \n#> #################### contrast 2 statistics ###################\n#> # A tibble: 3 × 3\n#>   DEGREE      mean_usetech sd.usetech\n#>   <ord>              <dbl>      <dbl>\n#> 1 <NA>                24.8       36.2\n#> 2 high school         49.6       38.6\n#> 3 all college         67.0       32.3\n#>  \n#> #################### contrast 3 statistics ###################\n#> # A tibble: 3 × 3\n#>   DEGREE              mean_usetech sd.usetech\n#>   <fct>                      <dbl>      <dbl>\n#> 1 jr college                  62.4       35.2\n#> 2 bach or grad degree         68.2       31.4\n#> 3 <NA>                        45.8       39.3\n#>  \n#> #################### contrast 4 statistics ###################\n#> # A tibble: 3 × 3\n#>   DEGREE   mean_usetech sd_usetech\n#>   <fct>           <dbl>      <dbl>\n#> 1 bachelor         67.9       32.1\n#> 2 graduate         68.7       30.2\n#> 3 <NA>             48.1       39.1\n```\n\n\n:::\n:::\n\n\n::::\n:::::\n\n\n\n\n:::\n\n::::\n:::::\n\n::: {.callout-tip}\nThe mean time spent on technology use at work was significantly different across educational attainment groups [F(4, 1404) = 43.3; p < .05], indicating these groups likely came from populations with different mean time spent on technology use. The highest mean was percent of time used for technology for those with graduate degrees. The lowest mean was percent of time for those with less than a high school diploma. A set of planned comparisons found that the mean time spent using technology was statistically significantly (p < .05) lower for (a) those with < high school education (m = 24.8) compared to those with high school or junior college (m = 51.7), (b) those with a high school education (m = 49.61) compared to those with all college groups combined (m = 67.0), (c) those with a junior college degree (m = 62.4) compared to those with a bachelor’s or graduate degree (m = 68.2), and (d) those with a bachelor’s degree (m = 67.9) compared to those with a graduate degree (m = 68.7). Overall, the patterns show statistically significant increases in time spent using technology at work for those with more education.\n:::\n\nHow many contrasts could be done and how all these statistical comparisons might be inflating the Type I error? --- In addition to each comparison comparing two things and each comparison adding to zero, the planned comparisons as a group should isolate each group (e.g., the high school group) *only one time*. This ensures that the contrasts are independent of each other since the variance for each group is only used by itself in a statistical comparison one time. Because each group is isolated one time, the total maximum number of contrasts allowable is one less than the number of groups.\n\n> When you have hypotheses ahead of time about which groups are different from one another, use <a class='glossary' title='Planned comparisons is a statistical strategy for comparing different groups, often used after a statistically significant analysis of variance to test hypotheses about which group means are statistically significantly different from one another. (SwR, Glossary)'>planned comparisons</a>. When you do not have hypotheses ahead of time about which means are different from each other, use post hoc tests if the ANOVA has a statistically significant <a class='glossary' title='F-statistic is a test statistic comparing explained and unexplained variance in [ANOVA] and linear regression. The F-statistic is a ratio where the variation between the groups is compared to the variation within the groups. (SwR, Glossary)'>F-statistic</a>. Good research practices suggest that having hypotheses ahead of time is a stronger strategy unless the research is truly exploratory.\n\n::: {#bul-characeristic-contrast}\n\n- Contrast values add to zero. \n- Each contrast compares two groups. \n- Each category is only isolated one time. \n- The maximum number of contrasts is one less than the number of categories.\n\nCharacteristics of contrasts\n\n:::\n\n## Achievement 4: Effect sizes for ANOVA {#sec-chap07-achievement4}\n\nSimilar as the effect size <a class='glossary' title='Cramér’s V is an effect size to determine the strength of the relationship between two categorical variables; often reported with the results of a chi-squared. (SwR, Glossary)'>Cramér’s V</a> for <a class='glossary' title='Chi-squared is the test statistic following the chi-squared probability distribution; the chi-squared test statistic is used in inferential tests, including examining the association between two categorical variables and determining statistical significance for a logistic regression model. (SwR, Glossary)'>chi-squared</a> tests and <a class='glossary' title='Cohen’s d is a standardized effect size for measuring the difference between two group means. It is frequently used to compare a treatment to a control group. It can be a suitable effect size to include with t-test and ANOVA results. (Statistics by Jim)'>Cohen’s d</a> for t-test, there are also effect size indices for ANOVA:\n\n- **<a class='glossary' title='Eta-squared is an [effect size] interpreted as the proportion of variability in the continuous outcome variable that is explained by groups in an analysis of variance; recent research suggests that eta-squared is biased and that [omega-squared] may be a less biased alternative following analysis of variance. (SwR, Glossary)'>eta-squared</a>**: It has a positive bias\n- **<a class='glossary' title='Omega-squared is an effect size for determining the strength of a relationship following an analysis of variance ([ANOVA]) statistical test. In contrast to [eta-squared] it is adjusted to account for the positive bias, and is more stable when assumptions are not completely met. (SwR, Glossary)'>omega-squared</a>**: An unbiased modern alternative\n\n:::::{.my-theorem}\n:::{.my-theorem-header}\n:::::: {#thm-chap07-omega-squared}\n: Formula for omega-squared\n::::::\n:::\n::::{.my-theorem-container}\n$$\n\\omega^2 = \\frac{F - 1}{f + \\frac{n-k+1}{k-1}}\n$$ {#eq-chap07-omega-squared}\n\n- **F**: Statistics from the ANOVA result\n- **n**: Number of observations\n- **k**: Number of groups\n\n::::\n:::::\n\n\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap07-omega-squared-manual}\n: Manual computation of effect size omega-squared\n::::::\n:::\n::::{.my-r-code-container}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngss_2018_clean <- base::readRDS(\"data/chap07/gss_2018_clean.rds\")\n\nusetech_degree_aov <- stats::aov(\n    formula = USETECH ~ DEGREE,\n    data = gss_2018_clean\n)\n\nglue::glue(\"############# ANOVA model USETECH ~ DEGREE ##################\")\n(\n    usetech_degree_aov_summary <- base::summary(usetech_degree_aov)\n)\n\nF_value = usetech_degree_aov_summary[[1]][[\"F value\"]][[1]]\nn = base::nrow(usetech_degree_aov[[\"model\"]])\nk = usetech_degree_aov[[\"rank\"]]\n\n\nglue::glue(\" \")\nglue::glue(\"############# Omega-squared ##################\")\nomega_squared <- (F_value - 1) / (F_value + ((n - k + 1) / (k - 1)))\nomega_squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> ############# ANOVA model USETECH ~ DEGREE ##################\n#>               Df  Sum Sq Mean Sq F value Pr(>F)    \n#> DEGREE         4  221301   55325    43.3 <2e-16 ***\n#> Residuals   1404 1793757    1278                   \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> 936 observations deleted due to missingness\n#>  \n#> ############# Omega-squared ##################\n#> [1] 0.1072194\n```\n\n\n:::\n:::\n\n***\n\n:::::{.my-watch-out}\n:::{.my-watch-out-header}\nWATCH OUT! Error in the book’s calculation\n:::\n::::{.my-watch-out-container}\nIn the first term in the book `-1` is missing! The formula is `F-1` that should be therefore `(summ.tech.anova[[1]][1, 4] -1)`. \n\nWith this correction we get the same value as in the manual calculation: 0.1072194.\n::::\n:::::\n\n::::\n:::::\n\n:::::{.my-assessment}\n:::{.my-assessment-header}\n:::::: {#cor-chap07-omega-squared}\n: Interpretation of omega-squared effect size\n::::::\n:::\n::::{.my-assessment-container}\n\n- **Small**: $ω^2 = .01 \\text{ to } ω^2 < .06$\n- **Medium**: $ω^2 = .06 \\text{ to } ω^2 < .14$\n- **Large**: $ω^2 ≥ .14$\n\n***\nThis is quite similar to the eta_squared ($\\eta^2$) assessment as listed in [Computation of Effect Sizes](https://www.psychometrica.de/effect_size.html). \n\n::::\n:::::\n\n::: {.callout-tip}\nThe mean time spent on technology use at work was significantly different across educational attainment groups [F(4, 1404) = 43.3; p < .05], indicating these groups likely came from populations with different mean time spent on technology use. The highest mean was percent of time used for technology for those with graduate degrees. The lowest mean was percent of time for those with less than a high school diploma. A set of planned comparisons found that the mean time spent using technology was statistically significantly (p < .05) lower for (a) those with < high school education (m = 24.8) compared to those with high school or junior college (m = 51.7), (b) those with a high school education (m = 49.61) compared to those with all college groups combined (m = 67.0), (c) those with a junior college degree (m = 62.4) compared to those with a bachelor’s or graduate degree (m = 68.2), and (d) those with a bachelor’s degree (m = 67.9) compared to those with a graduate degree (m = 68.7). Overall, the patterns show statistically significant increases in time spent using technology at work for those with more education. The strength of the relationship between degree and time using technology at work was medium ($ω^2$ = .11).\n:::\n\n## Achievement 5: Testing ANOVA assumptions {#sec-chap07-achievement5}\n\n0. **Continuous variable and independent groups**: This is the prerequisite for ANOVA.\n1. **Normality**: Each sample was drawn from a normally distributed population.\n2. **Equal Variances**: The variances of the populations that the samples come from are equal.\n3. **Independence**: The observations in each group are independent of each other and the observations within groups were obtained by a random sample.\n\n### Testing normality\n\n:::::{.my-example}\n:::{.my-example-header}\n:::::: {#exm-chap07-testing-normality}\n: Testing normality\n::::::\n:::\n::::{.my-example-container}\n\n::: {.panel-tabset}\n\n###### Density plot\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap07-testing-normality-density-plot}\n: Testing normality with density plots\n::::::\n:::\n::::{.my-r-code-container}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngss_2018_clean |> \n    tidyr::drop_na(USETECH) |> \n    ggplot2::ggplot(\n        ggplot2::aes(x = USETECH)\n    ) +\n    ggplot2::geom_density(\n        ggplot2::aes(\n            fill = DEGREE\n        )\n    ) +\n    ggplot2::facet_wrap(\n        facets = ggplot2::vars(DEGREE),\n        nrow = 2\n    ) +\n    ggokabeito::scale_fill_okabe_ito(guide = \"none\") +\n    ggplot2::labs(\n        x = \"Percent of time using tech\", \n        y = \"Probability density\")\n```\n\n::: {.cell-output-display}\n![Density Plot: Testing normality of time spent with technology at the job diferentiated by highest educational attainment](07-analysis-of-variance_files/figure-html/fig-testing-normality-density-plot-1.png){#fig-testing-normality-density-plot width=672}\n:::\n:::\n\n***\n\nNone of these graphs looks normally distributed!\n::::\n:::::\n\n###### Q-Q plot small\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap07-testing-normality-qq-plot1}\n: Testing normality with Q-Q plots\n::::::\n:::\n::::{.my-r-code-container}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngss_2018_clean  |> \n  tidyr::drop_na(USETECH) |>\n  \n  ggplot2::ggplot(\n      ggplot2::aes(sample = USETECH)\n      ) +\n  ggplot2::geom_abline(\n      ggplot2::aes(\n          intercept = mean(USETECH), \n          slope = sd(USETECH), \n          linetype = \"Normally distributed\"),\n          color = \"gray60\", \n          linewidth = 1\n      ) +\n  ggplot2::stat_qq(\n      ggplot2::aes(color = DEGREE)\n      ) +\n  ggokabeito::scale_color_okabe_ito(guide = \"none\") +\n  ggplot2::scale_linetype_manual(\n      name = \"\",\n      values = 1) +\n  ggplot2::labs(\n      x = \"Theoretical normal distribution\",\n      y = \"Observed values of percent time using tech\"\n      ) +\n  ggplot2::facet_wrap(\n      facets = ggplot2::vars(DEGREE), \n      nrow = 2\n      )\n```\n\n::: {.cell-output-display}\n![Q-Q Plot: Testing normality of time spent with technology at the job diferentiated by highest educational attainment](07-analysis-of-variance_files/figure-html/fig-testing-normality-qq-plot1-1.png){#fig-testing-normality-qq-plot1 width=672}\n:::\n:::\n\n\n***\n\nThe text in the books says that \"none of the groups appeared to be normally distributed based on either type of plot.\" This is ok for me with the density plot. But for me with not so much experience it is difficult to decide with the small Q-Q plots.\n\nThe next tab display the Q-Q plots for each group much bigger.\n\n::::\n:::::\n\n###### Q-Q plot big\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap07-testing-normality-qq-plot2}\n: Testing normality with Q-Q plots\n::::::\n:::\n::::{.my-r-code-container}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngss_2018_clean  |> \n  tidyr::drop_na(USETECH) |>\n  \n  ggplot2::ggplot(\n      ggplot2::aes(sample = USETECH)\n      ) +\n  ggplot2::geom_abline(\n      ggplot2::aes(\n          intercept = mean(USETECH), \n          slope = sd(USETECH), \n          linetype = \"Normally distributed\"),\n          color = \"gray60\", \n          linewidth = 1\n      ) +\n  ggplot2::stat_qq(\n      ggplot2::aes(color = DEGREE)\n      ) +\n  ggokabeito::scale_color_okabe_ito(guide = \"none\") +\n  ggplot2::scale_linetype_manual(\n      name = \"\",\n      values = 1) +\n  ggplot2::theme(legend.position = \"top\") +\n  ggplot2::labs(\n      x = \"Theoretical normal distribution\",\n      y = \"Observed values of percent time using tech\"\n      ) +\n  ggplot2::facet_wrap(\n      facets = ggplot2::vars(DEGREE), \n      nrow = 5\n      )\n```\n\n::: {.cell-output-display}\n![Q-Q Plot: Testing normality of time spent with technology at the job diferentiated by highest educational attainment](07-analysis-of-variance_files/figure-html/fig-testing-normality-qq-plot2-1.png){#fig-testing-normality-qq-plot2 width=672}\n:::\n:::\n\n***\n\nNow I can see it very clearly: All groups are not normally distributed. One can also observe that the floor and ceiling values are driving some of the non-normality.\n::::\n:::::\n\n###### Shapiro-Wilk test\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap07-testing-normality-shapiro-wilk}\n: Numbered R Code Title\n::::::\n:::\n::::{.my-r-code-container}\n\n::: {.cell}\n\n```{.r .cell-code}\nglue::glue(\"###### Test for the whole numeric USETECH vector #######\")\nstats::shapiro.test(gss_2018_clean$USETECH)\n\nglue::glue(\" \")\nglue::glue(\"###### Test for DEGREE groups of USETECH vector #######\")\ngss_2018_clean |> \n    dplyr::select(USETECH, DEGREE) |> \n    tidyr::drop_na() |> \n    dplyr::group_by(DEGREE) |> \n    dplyr::summarize(\n        shapiro_p_value = stats::shapiro.test(USETECH)$p.value\n    )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> ###### Test for the whole numeric USETECH vector #######\n#> \n#> \tShapiro-Wilk normality test\n#> \n#> data:  gss_2018_clean$USETECH\n#> W = 0.8645, p-value < 2.2e-16\n#> \n#>  \n#> ###### Test for DEGREE groups of USETECH vector #######\n#> # A tibble: 5 × 2\n#>   DEGREE         shapiro_p_value\n#>   <fct>                    <dbl>\n#> 1 < high school         1.83e-14\n#> 2 high school           5.99e-24\n#> 3 junior college        2.92e- 9\n#> 4 bachelor              1.22e-16\n#> 5 graduate              4.34e-11\n```\n\n\n:::\n:::\n\n\n***\n\nIn contrast with the systolic blood pressure data we have this time less than 5,000 observations and can therefore apply the <a class='glossary' title='The Shapiro-Wilk test is a statistical test to determine or confirm whether a variable has a normal distribution; it is sensitive to small deviations from normality and not useful for sample sizes above 5,000 because it will nearly always find non-normality. (SwR, Glossary)'>Shapiro-Wilk test</a>  (see @sec-chap06-omnibus-tests).\n\nAll five of the Shapiro-Wilk tests were statistically significant, indicating that the null hypothesis for this test (i.e., the data are normally distributed) has to be rejected for each group.\n::::\n:::::\n\n\n:::\n\n::::\n:::::\n\n### Testing homogeneity of variances\n\nThe data need to be not only normally distributed, but also spread out equally in each group, e.g. we need equal variances across groups.\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap07-testing-homogeneity-levine-test}\n: Levine’s test: Testing homogeneity of variances\n::::::\n:::\n::::{.my-r-code-container}\n\n::: {.cell}\n\n```{.r .cell-code}\ncar::leveneTest(\n    y = USETECH ~ DEGREE, \n    data = gss_2018_clean, \n    center = mean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Levene's Test for Homogeneity of Variance (center = mean)\n#>         Df F value    Pr(>F)    \n#> group    4  18.312 1.121e-14 ***\n#>       1404                      \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n***\nThe p-value for the Levene’s test suggests that we need to reject the null hypothesis. The variances of the `USETECH` variable are statistically significantly different across groups (p < .05). The ANOVA fails the assumption of homogeneity of variances.\n::::\n:::::\n\n## Achievement 6: Alternative tests for ANOVA (#sec-chap07-achivement6)\n\n## Exercises (empty)\n\n## Packages introduced in this chapter (empty)\n\n### dunn.test\n\n:::::{.my-resource}\n:::{.my-resource-header}\ndunn.test: Dunn's Test of Multiple Comparisons Using Rank Sums \n:::\n::::{.my-resource-container}\n\n***\n\n::: {#pak-dunn.test}\n\n***\n\n{**dunn.test**}: [Dunn's Test of Multiple Comparisons Using Rank Sums](https://cran.r-project.org/package=dunn.test) [@dunn.test]\n\nComputes Dunn's test [@dunn1964] for stochastic dominance and reports the results among multiple pairwise comparisons after a Kruskal-Wallis test for stochastic dominance among k groups [@kruskal1952. The interpretation of stochastic dominance requires an assumption that the CDF of one group does not cross the CDF of the other. \n\n{**dunn.test**} makes k(k-1)/2 multiple pairwise comparisons based on Dunn's z-test-statistic approximations to the actual rank statistics. The null hypothesis for each pairwise comparison is that the probability of observing a randomly selected value from the first group that is larger than a randomly selected value from the second group equals one half; this null hypothesis corresponds to that of the <a class='glossary' title='Mann-Whitney U test, also called Wilcoxon rank sum test, is an alternative for comparing a numeric or ordinal variable across two groups when the independent-samples t-test assumption of normality is not met. (SwR, Glossary)'>Wilcoxon-Mann-Whitney rank-sum test</a>. Like the rank-sum test, if the data can be assumed to be continuous, and the distributions are assumed identical except for a difference in location, Dunn's test may be understood as a test for median difference. {**dunn.test**} accounts for tied ranks.\n\n{**dunn.test**}: Dunn's Test of Multiple Comparisons Using Rank Sums\n:::\n\n***\n::::\n:::::\n\n\n## Glossary\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> term </th>\n   <th style=\"text-align:left;\"> definition </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> ANOVA </td>\n   <td style=\"text-align:left;\"> Analysis of variance is a statistical method used to compare means across groups to determine whether there is a statistically significant difference among the means; typically used when there are three or more means to compare. (SwR, Glossary) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Bonferroni </td>\n   <td style=\"text-align:left;\"> Bonferroni post hoc test is a pairwise test used after a statistically significant ANOVA that conducts a t-test for each pair of means but adjusts the threshold for statistical significance to ensure that there is a small enough risk of Type I error; it is generally considered a very conservative post hoc test that only identifies the largest differences between means as statistically significant. (SwR, Glossary) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Ceiling </td>\n   <td style=\"text-align:left;\"> A ceiling effect happens when many observations are at the highest possible value for a variable. (SwR, Glossary) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Chi-squared </td>\n   <td style=\"text-align:left;\"> Chi-squared is the test statistic following the chi-squared probability distribution; the chi-squared test statistic is used in inferential tests, including examining the association between two categorical variables and determining statistical significance for a logistic regression model. (SwR, Glossary) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Cohen’s d </td>\n   <td style=\"text-align:left;\"> Cohen’s d is a standardized effect size for measuring the difference between two group means. It is frequently used to compare a treatment to a control group. It can be a suitable effect size to include with t-test and ANOVA results. (&lt;a href= \"https://statisticsbyjim.com/basics/cohens-d/\"&gt;Statistics by Jim&lt;/a&gt;) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Contrasts </td>\n   <td style=\"text-align:left;\"> Contrasts are sets of numbers used in planned contrasts to specify which means or groups of means to compare to each other, usually to identify statistically significant differences among means after a statistically significant analysis of variance. (SwR, Glossary) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Cramér’s V </td>\n   <td style=\"text-align:left;\"> Cramér’s V is an effect size to determine the strength of the relationship between two categorical variables; often reported with the results of a chi-squared. (SwR, Glossary) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CVD </td>\n   <td style=\"text-align:left;\"> Color vision deficiency (CVD) or color blindness (also spelled colour blindness) includes a wide range of causes and conditions and is actually quite complex. It's a condition characterized by an inability or difficulty in perceiving and differentiating certain colors due to abnormalities in the three color-sensing pigments of the cones in the retina. (&lt;a href=\"https://enchroma.com/pages/types-of-color-blindness\"&gt;EnChroma&lt;/a&gt;) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Effect Size </td>\n   <td style=\"text-align:left;\"> Effect size is a measure of the strength of a relationship; effect sizes are important in inferential statistics in order to determine and communicate whether a statistically significant result has practical importance. (SwR, Glossary) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Eta-squared </td>\n   <td style=\"text-align:left;\"> Eta-squared is an [effect size] interpreted as the proportion of variability in the continuous outcome variable that is explained by groups in an analysis of variance; recent research suggests that eta-squared is biased and that [omega-squared] may be a less biased alternative following analysis of variance. (SwR, Glossary) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> F-Statistic </td>\n   <td style=\"text-align:left;\"> F-statistic is a test statistic comparing explained and unexplained variance in [ANOVA] and linear regression. The F-statistic is a ratio where the variation between the groups is compared to the variation within the groups. (SwR, Glossary) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Familywise </td>\n   <td style=\"text-align:left;\"> Familywise error is the alpha or Type I error rate when conducting multiple statistical tests. A large familywise alpha is one of the reasons that analysis of variance is preferable to conducting multiple t-tests when comparing means across more than two groups. (SwR, Glossary) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Floor </td>\n   <td style=\"text-align:left;\"> A floor effect happens when a variable has many observations that take the lowest value of the variable, which can indicate that the range of values was insufficient to capture the true variability of the data. (SwR, Glossary) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Grand </td>\n   <td style=\"text-align:left;\"> Grand mean is the overall mean of a continuous variable that is used to determine distances from the mean for individuals and groups in ANOVA. (SwR, Glossary) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> HSD </td>\n   <td style=\"text-align:left;\"> Tukey’s Honestly Significant Difference (HSD) is a post hoc test to determine which means are statistically significantly different from each other following a significant ANOVA result; Tukey’s HSD compares each pair of means and so is considered a pairwise test, but it is less conservative than the Bonferroni post hoc test. (SwR, Glossary) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Kurtosis </td>\n   <td style=\"text-align:left;\"> Kurtosis is a measure of how many observations are in the tails of a distribution; distributions that look bell-shaped, but have a lot of observations in the tails (platykurtic) or very few observations in the tails (leptokurtic) (SwR, Glossary) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Mann-Whitney </td>\n   <td style=\"text-align:left;\"> Mann-Whitney U test, also called Wilcoxon rank sum test, is an alternative for comparing a numeric or ordinal variable across two groups when the independent-samples t-test assumption of normality is not met. (SwR, Glossary) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Odds Ratio </td>\n   <td style=\"text-align:left;\"> Odds is usually defined in statistics as the probability an event will occur divided by the probability that it will not occur. An odds ratio (OR) is a measure of association between a certain property A and a second property B in a population. Specifically, it tells you how the presence or absence of property A has an effect on the presence or absence of property B. (&lt;a href=\"https://www.statisticshowto.com/probability-and-statistics/probability-main-index/odds-ratio/\"&gt;Statistics How To&lt;/a&gt;). An odds ratio is a ratio of two ratios. They quantify the strength of the relationship between two conditions. They indicate how likely an outcome is to occur in one context relative to another. (&lt;a href=\"https://statisticsbyjim.com/probability/odds-ratio/\"&gt;Statistics by Jim&lt;/a&gt;) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Omega-squared </td>\n   <td style=\"text-align:left;\"> Omega-squared is an effect size for determining the strength of a relationship following an analysis of variance ([ANOVA]) statistical test. In contrast to [eta-squared] it is adjusted to account for the positive bias, and is more stable when assumptions are not completely met. (SwR, Glossary) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Omnibus </td>\n   <td style=\"text-align:left;\"> An omnibus is a statistical test that identifies that there is some relationship going on between variables, but not what that relationship is. (SwR, Glossary) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> p-hacking </td>\n   <td style=\"text-align:left;\"> P-hacking is a set of statistical decisions and methodology choices during research that artificially produces statistically significant results. These decisions increase the probability of false positives—where the study indicates an effect exists when it actually does not. P-hacking is also known as data dredging, data fishing, and data snooping. (&lt;a href=\"https://statisticsbyjim.com/hypothesis-testing/p-hacking/\"&gt;Statistics by Jim&lt;/a&gt;) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> p-value </td>\n   <td style=\"text-align:left;\"> The p-value is the probability that the test statistic is at least as big as it is under the null hypothesis (SwR, Glossary) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Pairwise Comparisons </td>\n   <td style=\"text-align:left;\"> Pairwise comparisons are comparisons between every pair of groups to identify which are statistically significantly different from one another following a statistically significant result in an analysis of variance (ANOVA) or other multigroup analysis. (SwR, Glossary) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Planned Comparisons </td>\n   <td style=\"text-align:left;\"> Planned comparisons is a statistical strategy for comparing different groups, often used after a statistically significant analysis of variance to test hypotheses about which group means are statistically significantly different from one another. (SwR, Glossary) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Platykurtic </td>\n   <td style=\"text-align:left;\"> Platykurtic is a distribution of a numeric variable that has more observations in the tails than a normal distribution would have; platykurtic distributions often look flatter than a normal distribution. (SwR, Glossary) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Shapiro-Wilk </td>\n   <td style=\"text-align:left;\"> The Shapiro-Wilk test is a statistical test to determine or confirm whether a variable has a normal distribution; it is sensitive to small deviations from normality and not useful for sample sizes above 5,000 because it will nearly always find non-normality. (SwR, Glossary) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Standardized Residuals </td>\n   <td style=\"text-align:left;\"> Standardized residuals are the standardized differences between observed and expected values in a chi-squared analysis; a large standardized residual indicates that the observed and expected values were very different. (SwR, Glossary) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Student </td>\n   <td style=\"text-align:left;\"> Student t-test is a statistical test used to test whether the difference between the response of two groups is statistically significant or not. (&lt;a href=\"https://en.wikipedia.org/wiki/Student%27s_t-test\"&gt;Wikipedia&lt;/a&gt;) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> T-Test </td>\n   <td style=\"text-align:left;\"> A t-test is a type of statistical analysis used to compare the averages of two groups and determine whether the differences between them are more likely to arise from random chance. (&lt;a href=\"https://en.wikipedia.org/wiki/Student%27s_t-test\"&gt;Wikipedia&lt;/a&gt;) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Type-1 </td>\n   <td style=\"text-align:left;\"> Rejecting the null hypothesis when it should be retained is called Type I error or alpha and used as the threshold to determine statistical significance. (SwR, Glossary) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Type-2 </td>\n   <td style=\"text-align:left;\"> Retaining the null hypothesis when it should be rejected is calles Type II error or beta. (SwR, Glossary) </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n\n## Session Info {.unnumbered}\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\nSession Info\n:::\n::::{.my-r-code-container}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessioninfo::session_info()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> ─ Session info ───────────────────────────────────────────────────────────────\n#>  setting  value\n#>  version  R version 4.3.3 (2024-02-29)\n#>  os       macOS Sonoma 14.3.1\n#>  system   x86_64, darwin20\n#>  ui       X11\n#>  language (EN)\n#>  collate  en_US.UTF-8\n#>  ctype    en_US.UTF-8\n#>  tz       Europe/Vienna\n#>  date     2024-03-28\n#>  pandoc   3.1.12.3 @ /usr/local/bin/ (via rmarkdown)\n#> \n#> ─ Packages ───────────────────────────────────────────────────────────────────\n#>  package      * version    date (UTC) lib source\n#>  abind          1.4-5      2016-07-21 [1] CRAN (R 4.3.0)\n#>  car            3.1-2      2023-03-30 [1] CRAN (R 4.3.0)\n#>  carData        3.0-5      2022-01-06 [1] CRAN (R 4.3.0)\n#>  cli            3.6.2      2023-12-11 [1] CRAN (R 4.3.0)\n#>  colorblindr    0.1.0      2024-02-14 [1] Github (clauswilke/colorblindr@90d64f8)\n#>  colorspace     2.1-1      2024-01-03 [1] R-Forge (R 4.3.2)\n#>  commonmark     1.9.1      2024-01-30 [1] CRAN (R 4.3.2)\n#>  cowplot        1.1.3.9000 2024-02-14 [1] Github (wilkelab/cowplot@e1334a2)\n#>  crayon         1.5.2      2022-09-29 [1] CRAN (R 4.3.0)\n#>  curl           5.2.1      2024-03-01 [1] CRAN (R 4.3.2)\n#>  digest         0.6.35     2024-03-11 [1] CRAN (R 4.3.2)\n#>  dplyr          1.1.4      2023-11-17 [1] CRAN (R 4.3.0)\n#>  evaluate       0.23       2023-11-01 [1] CRAN (R 4.3.0)\n#>  fansi          1.0.6      2023-12-08 [1] CRAN (R 4.3.0)\n#>  farver         2.1.1      2022-07-06 [1] CRAN (R 4.3.0)\n#>  fastmap        1.1.1      2023-02-24 [1] CRAN (R 4.3.0)\n#>  forcats        1.0.0      2023-01-29 [1] CRAN (R 4.3.0)\n#>  generics       0.1.3      2022-07-05 [1] CRAN (R 4.3.0)\n#>  ggokabeito     0.1.0      2021-10-18 [1] CRAN (R 4.3.0)\n#>  ggplot2        3.5.0      2024-02-23 [1] CRAN (R 4.3.2)\n#>  glossary     * 1.0.0.9000 2023-08-12 [1] Github (debruine/glossary@819e329)\n#>  glue           1.7.0      2024-01-09 [1] CRAN (R 4.3.0)\n#>  gtable         0.3.4      2023-08-21 [1] CRAN (R 4.3.0)\n#>  highr          0.10       2022-12-22 [1] CRAN (R 4.3.0)\n#>  htmltools      0.5.7      2023-11-03 [1] CRAN (R 4.3.0)\n#>  htmlwidgets    1.6.4      2023-12-06 [1] CRAN (R 4.3.0)\n#>  jsonlite       1.8.8      2023-12-04 [1] CRAN (R 4.3.0)\n#>  kableExtra     1.4.0      2024-01-24 [1] CRAN (R 4.3.2)\n#>  knitr          1.45       2023-10-30 [1] CRAN (R 4.3.0)\n#>  labeling       0.4.3      2023-08-29 [1] CRAN (R 4.3.0)\n#>  lifecycle      1.0.4      2023-11-07 [1] CRAN (R 4.3.0)\n#>  magrittr       2.0.3      2022-03-30 [1] CRAN (R 4.3.0)\n#>  markdown       1.12       2023-12-06 [1] CRAN (R 4.3.0)\n#>  munsell        0.5.0      2018-06-12 [1] CRAN (R 4.3.0)\n#>  pillar         1.9.0      2023-03-22 [1] CRAN (R 4.3.0)\n#>  pkgconfig      2.0.3      2019-09-22 [1] CRAN (R 4.3.0)\n#>  purrr          1.0.2      2023-08-10 [1] CRAN (R 4.3.0)\n#>  R6             2.5.1      2021-08-19 [1] CRAN (R 4.3.0)\n#>  RColorBrewer   1.1-3      2022-04-03 [1] CRAN (R 4.3.0)\n#>  rlang          1.1.3      2024-01-10 [1] CRAN (R 4.3.0)\n#>  rmarkdown      2.26       2024-03-05 [1] CRAN (R 4.3.2)\n#>  rstudioapi     0.15.0     2023-07-07 [1] CRAN (R 4.3.0)\n#>  rversions      2.1.2      2022-08-31 [1] CRAN (R 4.3.0)\n#>  scales         1.3.0      2023-11-28 [1] CRAN (R 4.3.2)\n#>  sessioninfo    1.2.2      2021-12-06 [1] CRAN (R 4.3.0)\n#>  stringi        1.8.3      2023-12-11 [1] CRAN (R 4.3.0)\n#>  stringr        1.5.1      2023-11-14 [1] CRAN (R 4.3.0)\n#>  svglite        2.1.3      2023-12-08 [1] CRAN (R 4.3.0)\n#>  systemfonts    1.0.6      2024-03-07 [1] CRAN (R 4.3.2)\n#>  tibble         3.2.1      2023-03-20 [1] CRAN (R 4.3.0)\n#>  tidyr          1.3.1      2024-01-24 [1] CRAN (R 4.3.2)\n#>  tidyselect     1.2.1      2024-03-11 [1] CRAN (R 4.3.2)\n#>  utf8           1.2.4      2023-10-22 [1] CRAN (R 4.3.0)\n#>  vctrs          0.6.5      2023-12-01 [1] CRAN (R 4.3.2)\n#>  viridisLite    0.4.2      2023-05-02 [1] CRAN (R 4.3.0)\n#>  withr          3.0.0      2024-01-16 [1] CRAN (R 4.3.0)\n#>  xfun           0.42       2024-02-08 [1] CRAN (R 4.3.2)\n#>  xml2           1.3.6      2023-12-04 [1] CRAN (R 4.3.0)\n#>  yaml           2.3.8      2023-12-11 [1] CRAN (R 4.3.0)\n#> \n#>  [1] /Library/Frameworks/R.framework/Versions/4.3-x86_64/library\n#>  [2] /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library\n#> \n#> ──────────────────────────────────────────────────────────────────────────────\n```\n\n\n:::\n:::\n\n\n\n::::\n:::::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}