project:
  type: book

book:
  title: "Notes on Statistics with R (SWR)"
  author: "Peter Baumgartner"
  date: last-modified
  date-format: YYYY-MM-DD HH:mm
  favicon: "img/favicon_io/apple-touch-icon.png"
  site-url: https://bookdown.org/pbaumgartner/swr-harris/
  repo-url: https://github.com/petzi53/swr-harris
  repo-branch: master
  repo-actions: [edit, issue]

  chapters:
    - index.qmd
    - 01-preparing-data.qmd
    - 95-references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css:
     - quarto.css
     - glossary.css
    number-sections: true
    toc-depth: 5
    toc-expand: 4
    code-fold: true
    code-tools: true
    code-link: true
    code-overflow: scroll
    df-print: default

knitr:
  opts_chunk:
    comment: "#>"
    R.options:
      knitr.graphics.auto_pdf: true

editor: source

execute:
    freeze: auto

crossref:
  appendix-title: "Appendix"
  appendix-delim: ":"

language:
#   crossref-fig-title: "Graph"       # replaces "Figure"

   crossref-thm-title: "Theorem"
   crossref-lem-title: "Solution"    # replaces "Lemma"
   crossref-cor-title: "Note"        # replaces "Corollary"
   crossref-prp-title: "Procedure"   # replaces "Proposition"
   crossref-cnj-title: "R Code"      # replaces "Conjecture"
   crossref-def-title: "Definition"
   crossref-exm-title: "Example"
   crossref-exr-title: "Exercise"

# https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/language/_language.yml
   callout-tip-title: "Resource"         # green
   callout-note-title: "Note"            # blue
   callout-warning-title: "Watch out!"    # orange
   callout-important-title: "Important"  # red
   callout-caution-title: "Typo"         # yellow
