project:
  type: book

book:
  title: "Notes on Statistics with R (SwR)"
  author: "Peter Baumgartner"
  date: last-modified
  date-format: YYYY-MM-DD HH:mm
  favicon: "img/favicon_io/apple-touch-icon.png"
  site-url: https://bookdown.org/pbaumgartner/swr-harris/
  repo-url: https://github.com/petzi53/swr-harris
  repo-branch: master
  repo-actions: [edit, issue]

  chapters:
    - index.qmd
    - 01-preparing-data.qmd
    - 02-descriptive-statistics.qmd
    - 03-data-visualization.qmd
    - 95-references.qmd

bibliography:
    - references.bib
# reference-section-title: References
# citeproc: true


format:
  html:
    theme: cosmo
    css:
     - quarto.css
     - glossary.css
    number-sections: true
    toc-depth: 5
    toc-expand: 4
    toc_float: true
    code-fold: true
    code-tools: true
    code-link: true
    code-overflow: scroll
    df-print: default

filters:
   - include-code-files
#   - section-bibliographies

knitr:
  opts_chunk:
    comment: "#>"
    R.options:
      knitr.graphics.auto_pdf: true

editor: source

execute:
    freeze: auto

lightbox: true



crossref:
  appendix-title: "Appendix"
  appendix-delim: ":"
  custom:
    - kind: float
      reference-prefix: Important
      key: imp
    - kind: float
      reference-prefix: Commitment
      key: com
    - kind: float
      reference-prefix: Report
      key: rep
    - kind: float
      reference-prefix: Resource
      key: res
    - kind: float
      reference-prefix: Package Profile
      key: pak
    - kind: float
      reference-prefix: Bullet List
      key: bul
    - kind: float
      reference-prefix: Numerical List
      key: num

pak-cap-location: top
bul-cap-location: top

language:
   crossref-cnj-title: "R Code"      # replaces "Conjecture"
   crossref-cor-title: "Assessment"  # replaces "Corollary"
   crossref-def-title: "Experiment"  # replaces "Definition"
   crossref-exm-title: "Example"
   crossref-exr-title: "Exercise"
   crossref-fig-title: "Graph"       # replaces "Figure"
   crossref-lem-title: "Solution"    # replaces "Lemma"
   crossref-lst-title: "Listing"
   crossref-prp-title: "Procedure"   # replaces "Proposition"
   crossref-tbl-title: "Table"
   crossref-thm-title: "Theorem"
#   crossref-int-title: "Interpretation"

# https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/language/_language.yml
   callout-tip-title: "Report"           # green
   callout-note-title: "Note"            # blue
   callout-warning-title: "Watch out!"   # orange
   callout-important-title: "Important"  # red
   callout-caution-title: "Typo"         # yellow
