project:
  type: book

book:
  title: "Notes on Statistics with R (SwR)"
  author: "Peter Baumgartner"
  date: last-modified
  date-format: YYYY-MM-DD HH:mm
  favicon: "img/favicon_io/apple-touch-icon.png"
  site-url: https://bookdown.org/pbaumgartner/swr-harris/
  repo-url: https://github.com/petzi53/swr-harris
  repo-branch: master
  repo-actions: [edit, issue]

  chapters:
    - index.qmd
    - 01-preparing-data.qmd
    - 02-descriptive-statistics.qmd
    - 03-data-visualization.qmd
    - 04-probability-distributions.qmd
    - 05-chi-squared.qmd
    - 06-t-test.qmd
    - 07-analysis-of-variance.qmd
    - 08-correlation.qmd
    - 09-linear-regression.qmd
    - 95-references.qmd
  appendices:
    - 96-packages-used.qmd
    - 97-callout-boxes.qmd

bibliography:
    - references.bib
# reference-section-title: References
# citeproc: true


format:
  html:
    theme: cosmo
    css:
     - quarto.css
     - glossary.css
    number-sections: true
    toc-depth: 5
    toc-expand: 4
    toc_float: true
    code-fold: true
    code-tools: true
    code-link: true
    code-overflow: scroll
    df-print: default

filters:
   - include-code-files
#   - section-bibliographies

knitr:
  opts_chunk:
    comment: "#>"
    R.options:
      knitr.graphics.auto_pdf: true

editor: source

execute:
    freeze: auto

lightbox: true



crossref:
  appendix-title: "Appendix"
  appendix-delim: ":"
  custom:
    - key: rep
      kind: float
      reference-prefix: Report

    - key: res
      kind: float
      reference-prefix: Resource

    - key: pak
      kind: float
      reference-prefix: Package Profile

    - key: bul
      kind: float
      reference-prefix: Bullet List

    - key: not
      kind: float
      reference-prefix: Note

    - key: exp
      kind: float
      reference-prefix: Explanation

    - key: imp
      kind: float
      reference-prefix: Important

    - key: out
      kind: float
      reference-prefix: Output

    - key: wat
      kind: float
      reference-prefix: Watch-Out



tip-cap-location: top
pak-cap-location: top
bul-cap-location: bottom

language:
   crossref-cnj-title: "R Code"      # replaces "Conjecture"
   crossref-cor-title: "Assessment"  # replaces "Corollary"
   crossref-def-title: "Experiment"  # replaces "Definition"
   crossref-exm-title: "Example"     # remains  "Example"
   crossref-exr-title: "Exercise"    # remains  "Exercise"
   crossref-fig-title: "Graph"       # replaces "Figure"
   crossref-lem-title: "Resource"    # replaces "Lemma"
   crossref-lst-title: "Listing"     # remains  "Listing"
   crossref-prp-title: "Procedure"   # replaces "Proposition"
   crossref-tbl-title: "Table"       # remains  "Table"
   crossref-thm-title: "Formula"     # replaces "Theorem"
#   crossref-int-title: "Interpretation"

## Label Prefix	  Printed Name	LaTeX Environment

# 1. Figure, Tables and Listings
################################
#fig-             Figure       figure
#tbl-             Table        table
#lst-             Listing      listing

# 2. Theorems and friends
#########################
#cnj-	          Conjecture    conjecture
#cor-	          Corollary	    corollary
#def-	          Definition	definition
#exm-	          Example	    example
#exr-	          Exercise	    exercise
#lem-	          Lemma	        lemma
#prp-	          Proposition	proposition
#rem-	          Remark	    remark
#sol-	          Solution	    solution
#thm-	          Theorem	    theorem


# 3. Special cases
##################
#sec-             Section       section
#eq-              Equation      equation

# 4. Callout blocks
###################
#nte-             Note          note
#wrn-             Warning       warning
#imp              Important     important
#tip              Tip           tip
#cau              Caution       caution

# 5. Custom blocks
##################



# https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/language/_language.yml
   callout-tip-title: "Report"                  # green  = #tip
   callout-note-title: "Wording for H0 and HA"  # blue   = #nte
   callout-warning-title: "Watch out!"          # orange = #wrn
   callout-important-title: "Important"         # red    = #imp
   callout-caution-title: "Typo"                # yellow = #cau
