project:
  type: book

book:
  title: "Notes on Statistics with R (SWR)"
  author: "Peter Baumgartner"
  date: last-modified
  date-format: YYYY-MM-DD HH:mm
  favicon: "img/apple-touch-icon.png"
  site-url: https://bookdown.org/pbaumgartner/swr-harris/
  repo-url: https://github.com/petzi53/swr-harris
  repo-branch: master
  repo-actions: [edit, issue]

  chapters:
    - index.qmd
    - 01-intro.qmd
    - 95-references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css:
     - quarto.css
     - glossary.css
    number-sections: true
    toc-depth: 5
    toc-expand: 2
    code-fold: false
    code-tools: true
    code-link: true
    code-overflow: scroll
    df-print: default

knitr:
  opts_chunk:
    comment: "#>"
    R.options:
      knitr.graphics.auto_pdf: true

editor: visual

execute:
    freeze: auto

crossref:
  appendix-title: "Appendix"
  appendix-delim: ":"

language:
   crossref-fig-title: "Graph"
   crossref-prp-title: "Procedure"
   crossref-lem-title: "Solution"
   crossref-cnj-title: "R Code"


# https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/language/_language.yml
   callout-tip-title: "Tip"              # green
   callout-note-title: "Note"            # blue
   callout-warning-title: "Wach out!"    # orange
   callout-important-title: "Procedure"  # red
   callout-caution-title: "TODO"         # yellow

