{
  "hash": "bf826be82a23379a81cf558017d6fac5",
  "result": {
    "engine": "knitr",
    "markdown": "# Descriptive statistics {#sec-chap02}\n\n\n\n\n\n## Achievements to unlock\n\n::: my-objectives\n::: my-objectives-header\nObjectives\n:::\n\n::: my-objectives-container\n**SwR Achievements**\n\n-   **Achievement 1**: (~~Understanding variable types and data types~~)\n    (@sec-variable-data-types). As I already know this information I\n    will skip this achievement. This empty section is only mentioned to\n    get the same section numbering as in the book.\n-   **Achievement 2**: Choosing and conducting descriptive analyses for\n    categorical (factor) \n    variables (@sec-chap02-describe-categorical-variables)\n-   **Achievement 3**: Choosing and conducting descriptive analyses for\n    continuous (numeric) variables\n-   **Achievement 4**: Developing clear tables for reporting descriptive\n    statistics\n:::\n:::\n\n## The transgender health care problem\n\nSubject of this chapter is the transgender health care problem.\n\n-   <a class='glossary' title='People whose biological sex is not consistent with their gender. Contrast: Cisgender (SwR, Harris)'>Transgender</a> people are people whose biological sex\n    is not consistent with their gender.\n-   <a class='glossary' title='People whose gender identity matches their biological sex. Contrast: Transgender (SwR, Harris)'>Cisgender</a> people are people whose gender identity\n    matches their biological sex.\n\nThe rationale of this chapter is the fact, that prior to examining\nstatistical relationships among variables, published studies in academic\njournals usually present descriptive statistics. The following\nscreenshot from [@narayan2017a, p.876] demonstrates how such a\n<a class='glossary' title='Descriptive statistics are often displayed in the first table in a published article or report and are therefore often called Table 1 statistics or the descriptives. (SwR, Harris)'>Table 1</a> statistics might look:\n\n[![Screenshot of Table 1, \"Transgender Survey Participants Demographics\"\nfrom Narayan et. al.\n(2017)](img/chap02/table1-example-min.png){#fig-transgender-table1\nfig-alt=\"Screenshot of Table 1, \\\"Transgender Survey Participants Demographics\\\" from Narayan et. al. (2017)\"}](https://link.springer.com/article/10.1007/s10549-017-4461-8)\n\n## Data, codebook, and R packages\n\n::: my-resource\n::: my-resource-header\nData, codebook, and R packages for learning about descriptive statistics\n:::\n\n::: my-resource-container\n\n**Data**\n\nThere are two options:\n\n1.  Download the clean data file `transgender_hc_ch2.csv` from\n    <https://edge.sagepub.com/harris1e>.\n2.  Get the data file from the <a class='glossary' title='The Behavioral Risk Factor Surveillance System (BRFSS) is a system of health-related telephone surveys that collect state data about U.S. residents regarding their health-related risk behaviors, chronic health conditions, and use of preventive services. Established in 1984 with 15 states, BRFSS now collects data in all 50 states as well as the District of Columbia and three U.S. territories. BRFSS completes more than 400,000 adult interviews each year, making it the largest continuously conducted health survey system in the world. (BRFSS)'>BRFSS</a> website. (See\n    @lst-chap02-get-brfss-2014-data).\n    -   The page with the 2014 data is at\n        <https://www.cdc.gov/brfss/annual_data/annual_2014.html>.\n    -   The URL for the SAS transport file is at\n        <http://www.cdc.gov/brfss/annual_data/2014/files/LLCP2014XPT.zip>.\n\nThe ZIP-file is with 69 MB pretty big. Unzipped it will have almost 1\nGB! --- I will only work with this second option.\n\n**Codebook**\n\nAgain there are two options:\n\n1.  Download `brfss_2014_codebook.pdf` from\n    <https://edge.sagepub.com/harris1e>.\n2.  Download the codebook as PDF from the BRFSS webpage.\n    -   The location of the codebook is the same as above:\n        <https://www.cdc.gov/brfss/annual_data/annual_2014.html>.\n    -   The PDF codebook (2.74 MB) can be found at\n        [https://www.cdc.gov/brfss/annual_data/2014/pdf/CODEBOOK14_LLCP.pdf](https://www.cdc.gov/brfss/annual_data/annual_2014.html)\n\n**Packages**\n\n1. Packages used with the book (sorted alphabetically):\n   \n    - descr (@pak-descr)\n    - haven (@pak-haven)\n    - kableExtra\n    - knitr\n    - tidyverse (@pak-tidyverse)\n        - dplyr (@pak-dplyr)\n        - ggplot2 (@pak-ggplot2)\n        - forcats (@pak-forcats)\n        - tidyr (@pak-tidyr)\n    - tableone\n    - semTools \n    - qualvar \n    - labelled (@pak-labelled)\n    - Hmisc (@pak-Hmisc)\n    \n2. My additional packages (sorted alphabetically)\n\n    - gtsummary (See @pak-gtsummary)\n    - skimr (See @pak-skimr)\n\n\n\n:::\n:::\n\n## Understanding variable types and data types {#sec-variable-data-types}\n\nTo know about variable and data types is essential as different types\nrequire different approaches for the analysis.\n\nThe two most commonly used and reported descriptive statistics for\ncategorical (or factor) data types are frequencies and percentages.\n\nBut before we are going to work with the data we have do download it form the <a class='glossary' title='The Behavioral Risk Factor Surveillance System (BRFSS) is a system of health-related telephone surveys that collect state data about U.S. residents regarding their health-related risk behaviors, chronic health conditions, and use of preventive services. Established in 1984 with 15 states, BRFSS now collects data in all 50 states as well as the District of Columbia and three U.S. territories. BRFSS completes more than 400,000 adult interviews each year, making it the largest continuously conducted health survey system in the world. (BRFSS)'>BRFSS</a> website. \n\n\n\n::: {.callout-warning}\nDownloading the huge file (69 MB as ZIP and 1 GB unzipped) will take\nsome minutes. So be patient!\n:::\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\nDownload the SAS transport file data from the BRFSS website and save\ndataframe with selected variables as R object\n:::\n::::{.my-r-code-container}\n\n\n::: {#lst-chap02-get-brfss-2014-data}\n\n::: {.cell}\n\n```{.r .cell-code}\n## run this code chunk only once (manually)\n\nurl <- \"http://www.cdc.gov/brfss/annual_data/2014/files/LLCP2014XPT.zip\"\n\nutils::download.file(\n    url = url,\n    destfile = tf <- base::tempfile(),\n    mode = \"wb\"\n)\n\nbrfss_2014 <- haven::read_xpt(tf)\n\nbrfss_tg_2014 <- brfss_2014 |> \n    dplyr::select(\n        TRNSGNDR, \n        `_AGEG5YR`, \n        `_RACE`, \n        `_INCOMG`, \n        `_EDUCAG`, \n        HLTHPLN1, \n        HADMAM, \n        `_AGE80`, \n        PHYSHLTH)\n\ndata_folder <- base::paste0(here::here(), \"/data/\")\nif (!base::file.exists(data_folder)) \n    {base::dir.create(data_folder)}\n\nchap02_folder <- base::paste0(here::here(), \"/data/chap02/\")\nif (!base::file.exists(chap02_folder)) \n    {base::dir.create(chap02_folder)}\n\nbase::saveRDS(object = brfss_tg_2014, \n        file = paste0(chap02_folder, \"/brfss_tg_2014_raw.rds\"))\n```\n:::\n\n\nDownload and save the transgender data 2014 from the BRFSS website\n:::\n\nThe original file has 279 variables and 464664 observations. After selecting\nonly 9 variable the file is with 31.9 MB (memory usage) and stored\ncompressed (2.2 MB) much smaller.\n\n::: my-note\n::: my-note-header\nFour observations about the code\n:::\n\n::: my-note-container\n1.  It is not possible to download the file with\n    `haven::read_xpt(<URL>)` directly. At first one has to create a\n    temporary file to store the zipped file.\n2.  Whenever you meet a variable / row name with a forbidden R syntax\n    surround the name with <a class='glossary' title='The backtick ` is a typographical mark used mainly in computing. It is also known as backquote, grave, or grave accent. (Wikipedia)'>backticks</a> ([grave\n    accents](https://en.wikipedia.org/wiki/Grave_accent)).\n3.  Instead of exporting the R object into a <a class='glossary' title='Text files where the values are separated with commas (Comma Separated Values = CSV). These files have the file extension .csv'>.csv</a>\n    file I save the data as a compressed R object that can loaded easily\n    again into the computer memory with the `base::readRDS()` function.\n4.  With regard to the `base::saveRDS()` function I have to remind\n    myself that the first argument is the R object *without* quotes. I\n    committed this error several times.\n:::\n:::\n\n\n\n\n::::\n:::::\n\n\n\n## Descriptive analyses for categorical (factor) variables {#sec-chap02-describe-categorical-variables}\n\nThe goal of this section is to summarize and interpret the categorical variable `TRNSGNDR`. In contrast to the book I will work with a dataframe consisting only of the variable which I will recode to `transgender`. The tabs of \n\n\n### Interpret categorical variables\n\n::: my-example\n::: my-example-header\n::: {#exm-chap02-interpret-categorical-variables}\n: Recode, summarize and interpret categorical variables\n:::\n:::\n\n::: my-example-container\n\n::: panel-tabset\n\n###### select()\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchap02_folder <- base::paste0(here::here(), \"/data/chap02/\")\ntransgender_pb <- \n    base::readRDS(base::paste0(chap02_folder, \n           \"brfss_tg_2014_raw.rds\")) |> \n    dplyr::select(TRNSGNDR)\n\nbase::saveRDS(object = transgender_pb, \n        file = base::paste0(chap02_folder, \"transgender_pb.rds\"))\n```\n:::\n\n\n\n\n###### str()\n\n::: my-r-code\n::: my-r-code-header\n::: {#cnj-chap02-str-transgender}\n: Show structure of the `transgender` data with `utils::str()`\n:::\n:::\n\n::: my-r-code-container\n\n::: {.cell}\n\n```{.r .cell-code}\nutils::str(transgender_pb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> tibble [464,664 × 1] (S3: tbl_df/tbl/data.frame)\n#>  $ TRNSGNDR: num [1:464664] NA NA NA NA NA NA NA NA NA NA ...\n#>   ..- attr(*, \"label\")= chr \"DO YOU CONSIDER YOURSELF TO BE TRANSGEND\"\n```\n\n\n:::\n:::\n\n\n{**haven**} has imported <a class='glossary' title='Labelled data (or labelled vectors) is a common data structure in other statistical environments to store meta-information about variables, like variable names, value labels or multiple defined missing values. (sjlabelled)'>labelled data</a> for the variables. We can use these labels to find the appropriate passages in the 126 pages of the\ncodebook. Just copy the variable label and search this string in\nthe PDF of the codebook.\n\n------------------------------------------------------------------------\n\n![Behavior Risk Factor Surveillance Systems (BRFSS) Codebook Report,\n2014 Land-Line and Cell-Phone\ndata](img/chap02/transgender-codebook-min.png){#fig-chap02-codebook-transgender\nfig-alt=\"The table displays the sexual orientation and gender identity as an answer of the question 'Do you consider yourself to be transgender?' - The answers were: Yes, male-to-female: 363; Yes, female-to-male: 212; Yes, gender nonconforming: 116; No: 150,765; Don't know / Not sure: 1,138; Refused: 1,468; Not asked or missing: 310,602.\"}\n:::\n:::\n\nNote that variable labels are restricted to 40 characters. I think\nthis is an import limitation of {**haven**} because there is no such\nrestriction using `haven::labelled()`. But we need to recode the data\nanyway, especially as there are no value labels available.\n\n###### summary()\n\n::: my-r-code\n::: my-r-code-header\n::: {#cnj-chap02-summary-transgender}\n: Summarize `transgender` data with `base::summary()`\n:::\n:::\n\n::: my-r-code-container\n\n::: {.cell}\n\n```{.r .cell-code}\nbase::summary(transgender_pb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>     TRNSGNDR     \n#>  Min.   :1.00    \n#>  1st Qu.:4.00    \n#>  Median :4.00    \n#>  Mean   :4.06    \n#>  3rd Qu.:4.00    \n#>  Max.   :9.00    \n#>  NA's   :310602\n```\n\n\n:::\n:::\n\n:::\n:::\n\n###### skim()\n\n::: my-r-code\n::: my-r-code-header\n::: {#cnj-chap02-skim-transgender}\n: Summarize transgender data with `skimr::skim()`\n:::\n:::\n\n::: my-r-code-container\n\n::: {.cell}\n\n```{.r .cell-code}\nskimr::skim(transgender_pb)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |               |\n|:------------------------|:--------------|\n|Name                     |transgender_pb |\n|Number of rows           |464664         |\n|Number of columns        |1              |\n|_______________________  |               |\n|Column type frequency:   |               |\n|numeric                  |1              |\n|________________________ |               |\n|Group variables          |None           |\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate| mean|   sd| p0| p25| p50| p75| p100|hist  |\n|:-------------|---------:|-------------:|----:|----:|--:|---:|---:|---:|----:|:-----|\n|TRNSGNDR      |    310602|          0.33| 4.06| 0.57|  1|   4|   4|   4|    9|▁▇▁▁▁ |\n\n\n:::\n:::\n\n:::\n:::\n\n###### gtsummary()\n\n::: my-r-code\n::: my-r-code-header\n::: {#cnj-chap02-gtsummary-transgender}\n: Summarize and display transgender data with `gtsummary::tbl_summary()`\n:::\n:::\n\n::: my-r-code-container\n\n::: {#tbl-gtsummary-transgender .cell tbl-cap='A firt approach to produce a \\'Table 1\\' statistics with {gtsummary} using labelled data'}\n\n```{.r .cell-code}\ngtsummary::tbl_summary(transgender_pb)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"iwzoyittdg\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#iwzoyittdg table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#iwzoyittdg thead, #iwzoyittdg tbody, #iwzoyittdg tfoot, #iwzoyittdg tr, #iwzoyittdg td, #iwzoyittdg th {\n  border-style: none;\n}\n\n#iwzoyittdg p {\n  margin: 0;\n  padding: 0;\n}\n\n#iwzoyittdg .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#iwzoyittdg .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#iwzoyittdg .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#iwzoyittdg .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#iwzoyittdg .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#iwzoyittdg .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iwzoyittdg .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#iwzoyittdg .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#iwzoyittdg .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#iwzoyittdg .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#iwzoyittdg .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#iwzoyittdg .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#iwzoyittdg .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#iwzoyittdg .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#iwzoyittdg .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#iwzoyittdg .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#iwzoyittdg .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#iwzoyittdg .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#iwzoyittdg .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iwzoyittdg .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#iwzoyittdg .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#iwzoyittdg .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#iwzoyittdg .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iwzoyittdg .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#iwzoyittdg .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#iwzoyittdg .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iwzoyittdg .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iwzoyittdg .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#iwzoyittdg .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iwzoyittdg .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#iwzoyittdg .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iwzoyittdg .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#iwzoyittdg .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iwzoyittdg .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#iwzoyittdg .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iwzoyittdg .gt_left {\n  text-align: left;\n}\n\n#iwzoyittdg .gt_center {\n  text-align: center;\n}\n\n#iwzoyittdg .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#iwzoyittdg .gt_font_normal {\n  font-weight: normal;\n}\n\n#iwzoyittdg .gt_font_bold {\n  font-weight: bold;\n}\n\n#iwzoyittdg .gt_font_italic {\n  font-style: italic;\n}\n\n#iwzoyittdg .gt_super {\n  font-size: 65%;\n}\n\n#iwzoyittdg .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#iwzoyittdg .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#iwzoyittdg .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#iwzoyittdg .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#iwzoyittdg .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#iwzoyittdg .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#iwzoyittdg .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;N = 464,664&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>N = 464,664</strong><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">DO YOU CONSIDER YOURSELF TO BE TRANSGEND</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">363 (0.2%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    2</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">212 (0.1%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    3</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">116 (&lt;0.1%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    4</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">150,765 (98%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    7</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">1,138 (0.7%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    9</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">1,468 (1.0%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Unknown</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">310,602</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"2\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span> n (%)</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n{**gtsummary**} uses here the labelled data imported with {**haven**}.\nNot bad, isn't it? Just a one-liner produces this first trial for a pbulic ready\n<a class='glossary' title='Descriptive statistics are often displayed in the first table in a published article or report and are therefore often called Table 1 statistics or the descriptives. (SwR, Harris)'>Table 1</a> statistics. This first attempt of table would be\neven better if the data had also value labels. \n\nFor more\ninformation how to work with with labelled data see the full\n@sec-chap01-labelled-data with all its sub-sections. You will find\nsome functions how to adapt @tbl-gtsummary-transgender to get a better\ndescriptive in @sec-chap01-intro-gtsummary. But follow also this chapter\nalong!\n:::\n:::\n\n:::\n\n:::\n:::\n\n### Data management\n\nWe need to manipulate data to provide a table with all its required\nfeatures as they are:\n\n***\n\n::: {#bul-chap02-table-features}\n\n***\n1. A main title indicating what is in the table, including\n    -   the overall sample size\n    -   key pieces of information that describe the data such as the year of data collection and the data source\n2. Clear column and row labels that have \n    - logical row and column names\n    - a clear indication of what the data are, such as means or frequencies\n    - row and column sample sizes when they are different from overall\n    sample sizes [@harris2020].\n    \nRequired features of a table\n:::\n\n***\n\n::: my-example\n::: my-example-header\n::: {#exm-chap02-data-wrnagling-categorical}\n: Data management with categorical variable\n:::\n:::\n\n::: my-example-container\n::: panel-tabset\n###### table()\n\n::: my-r-code\n::: my-r-code-header\n::: {#cnj-code-name-a}\n: Using table() to count factor levels\n:::\n:::\n\n::: my-r-code-container\n\n::: {.cell}\n\n```{.r .cell-code}\n## load transgender_pb ##########\nchap02_folder <- base::paste0(here::here(), \"/data/chap02/\")\ntransgender_pb <- \n    base::readRDS(base::paste0(chap02_folder, \"transgender_pb.rds\"))\n\nbase::table(transgender_pb$TRNSGNDR)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#>      1      2      3      4      7      9 \n#>    363    212    116 150765   1138   1468\n```\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\nCompare the values with the screenshot from the codebook in\n@fig-chap02-codebook-transgender.\n:::\n:::\n\nNormally `table()` is used for cross-classifying factors to build a contingency table of the counts at each combination of factor levels. But here I have only one variable.\n\n###### class()\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap02-class-transgender}\n: Numbered R Code Title\n::::::\n:::\n::::{.my-r-code-container}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(transgender_pb$TRNSGNDR)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] \"numeric\"\n```\n\n\n:::\n:::\n\n\n\n::::\n:::::\n\n\n###### as_factor\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntransgender_pb$TRNSGNDR <- \n    forcats::as_factor(transgender_pb$TRNSGNDR)\nclass(transgender_pb$TRNSGNDR)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] \"factor\"\n```\n\n\n:::\n:::\n\n\n\n###### fct_recode()\n\n::: my-r-code\n::: my-r-code-header\n::: {#cnj-chap02-recode-transgender}\nb: Numbered R Code Title (Tidyverse)\n:::\n:::\n\n::: my-r-code-container\n\n::: {.cell}\n\n```{.r .cell-code}\ntransgender_clean <- transgender_pb |> \n    dplyr::mutate(TRNSGNDR = forcats::fct_recode(TRNSGNDR,\n        \"Male to female\" = '1',\n        \"Female to male\" = '2',\n        \"Gender nonconforming\" = '3',\n        \"Not transgender\" = '4',\n        \"Don’t know/Not sure\" = '7',\n        \"Refused\" = '9'\n    )) \n\nchap02_folder <- base::paste0(here::here(), \"/data/chap02/\")\nbase::saveRDS(object = transgender_clean, \n        file = base::paste0(chap02_folder, \"transgender_clean.rds\"))\n\nbase::summary(transgender_clean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>                  TRNSGNDR     \n#>  Male to female      :   363  \n#>  Female to male      :   212  \n#>  Gender nonconforming:   116  \n#>  Not transgender     :150765  \n#>  Don’t know/Not sure :  1138  \n#>  Refused             :  1468  \n#>  NA's                :310602\n```\n\n\n:::\n:::\n\n:::\n:::\n\nHarris explains in the book the superseded function `dplyr::recode_factor()`. It's new equivalent is now `forcats::fct_recode()`.\n\n###### describe()\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap02-describe-transgender}\n: Numbered R Code Title\n::::::\n:::\n::::{.my-r-code-container}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## load transgender_clean ##########\nchap02_folder <- base::paste0(here::here(), \"/data/chap02/\")\ntransgender_clean <- \n    base::readRDS(base::paste0(chap02_folder, \"transgender_clean.rds\"))\n\nHmisc::describe(transgender_clean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> transgender_clean \n#> \n#>  1  Variables      464664  Observations\n#> --------------------------------------------------------------------------------\n#> TRNSGNDR \n#>        n  missing distinct \n#>   154062   310602        6 \n#>                                                                          \n#> Value            Male to female       Female to male Gender nonconforming\n#> Frequency                   363                  212                  116\n#> Proportion                0.002                0.001                0.001\n#>                                                                          \n#> Value           Not transgender  Don’t know/Not sure              Refused\n#> Frequency                150765                 1138                 1468\n#> Proportion                0.979                0.007                0.010\n#> --------------------------------------------------------------------------------\n```\n\n\n:::\n:::\n\n***\n\n`Hmisc::describe()` is a completely new function for me. Sometimes I met in my reading the {**Hmisc**} package, but I have never applied functions independently. \n\n***\n\n::: {#pak-Hmisc}\n\n***\n\n{**Hmisc**}: [Harrell Miscellaneous](https://hbiostat.org/r/hmisc/)\n\nThere is no hexagon sticker available for {**Hmisc**}.\n\n::: {layout=\"[10, 30]\" layout-valign=\"center\"}\n![](https://www.fharrell.com/profile.jpg){width=\"176\"}\n\n\n\nContains many functions useful for \n\n- data analysis, \n- high-level graphics, \n- utility operations, \n- computing sample size and power, \n- simulation, \n- importing and annotating datasets,\n- imputing missing values, \n- advanced table making, \n- variable clustering,\n- character string manipulation, \n- conversion of R objects to {{< latex >}} and HTML code,\n- recoding variables, \n- caching, \n- simplified parallel computing, \n- encrypting and decrypting data using a safe workflow, \n- general moving window statistical estimation, \n- assistance in interpreting principal component analysis [@Hmisc]\n\n\n:::\n\nThis is big variety of functions. In contrast to other packages that are specific directed to solve one problem {**Hmisc**} seems to be an all-in-one-solution.\n\n\nHmisc a package for miscellaneous functions for data analysis and related tasks\n\n:::\n\nTo learn more about I should visit Frank E. Harrell's Jr [Hmisc startig page](https://hbiostat.org/r/hmisc/) and read especially his [book on workflow](https://hbiostat.org/rflow/) that seems to me very interesting.\n\n***\n\n\n\n\n::::\n:::::\n\n###### freq()\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap02-freq-transgender}\n: Using the {desc} package\n::::::\n:::\n::::{.my-r-code-container}\n\n::: {#lst-chap02-freq-transgender}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndescr::freq(transgender_clean$TRNSGNDR, plot = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> transgender_clean$TRNSGNDR \n#>                      Frequency   Percent Valid Percent\n#> Male to female             363   0.07812       0.23562\n#> Female to male             212   0.04562       0.13761\n#> Gender nonconforming       116   0.02496       0.07529\n#> Not transgender         150765  32.44603      97.85995\n#> Don’t know/Not sure       1138   0.24491       0.73866\n#> Refused                   1468   0.31593       0.95286\n#> NA's                    310602  66.84443              \n#> Total                   464664 100.00000     100.00000\n```\n\n\n:::\n:::\n\n\nUsing `descr::freq()` to calculate values with and without NA's\n:::\n\nThis is the first time that I used the {**descr**} package. Searching for more information on CRAN I noticed that there are at least 10 other packages for facilitate descriptive statistics!\n\n::::\n:::::\n\n***\n\n::: {#pak-descr}\n\n***\n\n{**descr**}: [Descriptive Statistics](https://github.com/jalvesaq/descr)\n\nThere is no logo available for {**descr**}\n\n\nWeighted frequency and contingency tables of categorical variables and of the comparison of the mean value of a numerical variable by the levels of a factor, and methods to produce xtable objects of the tables and to plot them. There are also functions to facilitate the character encoding conversion of objects, to quickly convert fixed width files into csv ones, and to export a data.frame to a text file with the necessary R and SPSS codes to reread the data. [@descr]\n\nPackage for Descriptive Statistics\n:::\n\n***\n\n\n\n###### {dplyr}\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap02-dplyr-transgender}\n: Numbered R Code Title\n::::::\n:::\n::::{.my-r-code-container}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntransgender_clean |> \n    dplyr::group_by(TRNSGNDR) |> \n    dplyr::summarize(n = dplyr::n()) |> \n    dplyr::mutate(perc = n / sum(n) * 100)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 7 × 3\n#>   TRNSGNDR                  n    perc\n#>   <fct>                 <int>   <dbl>\n#> 1 Male to female          363  0.0781\n#> 2 Female to male          212  0.0456\n#> 3 Gender nonconforming    116  0.0250\n#> 4 Not transgender      150765 32.4   \n#> 5 Don’t know/Not sure    1138  0.245 \n#> 6 Refused                1468  0.316 \n#> 7 <NA>                 310602 66.8\n```\n\n\n:::\n:::\n\n\n\n::::\n:::::\n\n###### {report}\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap02-report-transgender}\nUsing `report::report_table()` to summarize the result\n::::::\n:::\n::::{.my-r-code-container}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreport::report_table(transgender_clean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nVariable |                Level |  n_Obs | percentage_Obs\n---------------------------------------------------------\nTRNSGNDR |       Male to female |    363 |           0.08\nTRNSGNDR |       Female to male |    212 |           0.05\nTRNSGNDR | Gender nonconforming |    116 |           0.02\nTRNSGNDR |      Not transgender | 150765 |          32.45\nTRNSGNDR |  Don’t know/Not sure |   1138 |           0.24\nTRNSGNDR |              Refused |   1468 |           0.32\nTRNSGNDR |              missing | 310602 |          66.84\n```\n\n\n:::\n:::\n\n\nI just learned about the existence of {**report**}. It is specialized to facilitate reporting of results and statistical models. In this example I have used the `report::report_table()` function because the result of the standard `report::report()` is rather underwhelming as you can see: \n\n***\n\nThe data contains 464664 observations of the following 1 variables:\n\n  - TRNSGNDR: 6 levels, namely Male to female (n = 363, 0.08%), Female to male (n = 212, 0.05%), Gender nonconforming (n = 116, 0.02%), Not transgender (n = 150765, 32.45%), Don’t know/Not sure (n = 1138, 0.24%), Refused (n = 1468, 0.32%) and missing (n = 310602, 66.84%)\n\n***\n\nCompare this to the example of the book:\n\n::: {#rep-chap02-transgender1}\n::: {.callout-tip style=\"color: darkgreen;\"}\nThe 2014 BRFSS had a total of 464,664 participants. Of these, 310,602 (66.8%) were not asked or were otherwise missing a response to the <a class='glossary' title='People whose biological sex is not consistent with their gender. Contrast: Cisgender (SwR, Harris)'>transgender</a> status question. A few participants refused to answer (n = 1,468; 0.32%), and a small number were unsure of their status (n = 1,138; 0.24%). Most reported being not transgender (n = 150,765; 32.4%), 116 were <a class='glossary' title='Gender nonconforming means not adhering to society’s gender norms. People may describe themselves as gender nonconforming if they don’t conform to the gender expression, presentation, behaviors, roles, or expectations that society sees as the norm for their gender. (APA Guidelines - PDF)'>gender non-conforming</a> (0.03%), 212 were female to male (0.05%), and 363 were male to female (0.08%).\n:::\n\nDo you consider yourself to be transgender? (Figures with missing values)\n\n:::\n\n(There is another report of the `TRNSGNDR` without the many `NA`s: See @rep-chap02-transgender2 for a comparison.)\n\nBut it seems to me that with more complex results (e.g., from models) it seems to me that {**report**} quite usable. Following the book I will try it out and compare with the book’s reports.\n\n***\n\nAnother thought: I have filed an issue because I think that it would be a great idea to provide a markdown compatible table so that Quarto resp. pandoc could interpret as a table and visualizing it accordingly. The table above would then appear as the following (copied and slightly edited) example:\n\n\nVariable |                Level |  n_Obs | percentage_Obs\n---------|----------------------|--------|----------------\nTRNSGNDR |       Male to female |    363 |           0.08\nTRNSGNDR |       Female to male |    212 |           0.05\nTRNSGNDR | Gender nonconforming |    116 |           0.02\nTRNSGNDR |      Not transgender | 150765 |          32.45\nTRNSGNDR |  Don’t know/Not sure |   1138 |           0.24\nTRNSGNDR |              Refused |   1468 |           0.32\nTRNSGNDR |              missing | 310602 |          66.84\n\n: Slightly modified {**report**} table to get a Markdown compatible table\n\n::::\n:::::\n\n***\n\n::: {#pak-report}\n\n***\n\n{**report**}: [Automated Reporting of Results and Statistical Models](URL to package)\n\n::: {layout=\"[10, 30]\" layout-valign=\"center\"}\n![](img/chap02/logoi/logo-report-min.png){width=\"176\"}\n\nThe primary goal of {**report**} is to bridge the gap between R’s output and the formatted results contained in your manuscript. It automatically produces reports of models and data frames according to best practices guidelines (e.g., APA’s style), ensuring standardization and quality in results reporting.\n\n:::\n\nReport Package for Automated Reporting of Results and Statistical Models\n:::\n\n<Other text not included in the reference>\n\n***\n\n###### na.omit()\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap02-na-omit-transgender}\n: Numbered R Code Title\n::::::\n:::\n::::{.my-r-code-container}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntransgender_clean |> \n    dplyr::group_by(TRNSGNDR) |> \n    dplyr::summarize(n = dplyr::n()) |> \n    dplyr::mutate(perc_all = 100 * (n / sum(n))) |> \n    dplyr::mutate(perc_valid = 100 * (n / sum(n[na.omit(TRNSGNDR)])))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 7 × 4\n#>   TRNSGNDR                  n perc_all perc_valid\n#>   <fct>                 <int>    <dbl>      <dbl>\n#> 1 Male to female          363   0.0781     0.236 \n#> 2 Female to male          212   0.0456     0.138 \n#> 3 Gender nonconforming    116   0.0250     0.0753\n#> 4 Not transgender      150765  32.4       97.9   \n#> 5 Don’t know/Not sure    1138   0.245      0.739 \n#> 6 Refused                1468   0.316      0.953 \n#> 7 <NA>                 310602  66.8      202.\n```\n\n\n:::\n:::\n\n::::\n:::::\n\n:::::{.my-watch-out}\n:::{.my-watch-out-header}\nWATCH OUT! Wrong `perc_valid` cell value in `NA` row\n:::\n::::{.my-watch-out-container}\n\nI have the same logic used as in the book. But the result is not the same as in @lst-chap02-freq-transgender. The `perc_valid` cell value in the `NA` row should be empty, but it shows the value 202 (rounded).\n:::::\n::::\n\n###### full_join()\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap02-full-join-transgender}\n: Numbered R Code Title\n::::::\n:::\n::::{.my-r-code-container}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntg1 <- transgender_clean |> \n    dplyr::group_by(TRNSGNDR) |> \n    dplyr::summarize(n = dplyr::n()) |> \n    dplyr::mutate(perc_all = 100 * (n / sum(n)))\n\ntg2 <- transgender_clean |> \n    dplyr::group_by(TRNSGNDR) |> \n    tidyr::drop_na() |> \n    dplyr::summarize(n = dplyr::n()) |> \n    dplyr::mutate(perc_valid = 100 * (n / sum(n)))\n\ndplyr::full_join(tg1, tg2, by = dplyr::join_by(TRNSGNDR, n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 7 × 4\n#>   TRNSGNDR                  n perc_all perc_valid\n#>   <fct>                 <int>    <dbl>      <dbl>\n#> 1 Male to female          363   0.0781     0.236 \n#> 2 Female to male          212   0.0456     0.138 \n#> 3 Gender nonconforming    116   0.0250     0.0753\n#> 4 Not transgender      150765  32.4       97.9   \n#> 5 Don’t know/Not sure    1138   0.245      0.739 \n#> 6 Refused                1468   0.316      0.953 \n#> 7 <NA>                 310602  66.8       NA\n```\n\n\n:::\n:::\n\n\nAlthough this code with packages from the {**tidayverse**} collection is more verbose than @lst-chap02-freq-transgender using {**descr**} it has the advantage that one does not need to install and learn a new package.\n\n\n::::\n:::::\n\n::: {#rep-chap02-transgender2}\n::: {.callout-tip style=\"color: darkgreen;\"}\nThe 2014 BRFSS had a total of 464,664 participants. Of these, 310,602 (66.8%) were not asked or were otherwise missing a response to the <a class='glossary' title='People whose biological sex is not consistent with their gender. Contrast: Cisgender (SwR, Harris)'>transgender</a> status question. Of the 33.2% who responded, some refused to answer (n = 1,468; 0.95%), and a small number were unsure of their status (n = 1,138, 0.74%). Most reported being not transgender (n = 150,765; 97.9%), 116 were <a class='glossary' title='Gender nonconforming means not adhering to society’s gender norms. People may describe themselves as gender nonconforming if they don’t conform to the gender expression, presentation, behaviors, roles, or expectations that society sees as the norm for their gender. (APA Guidelines - PDF)'>gender non-conforming</a>  (0.08%), 212 were female to male (0.14%), and 363 were male to female (0.24%).\n:::\n\nDo you consider yourself to be transgender? (Figures without missing values)\n\n:::\n\nCompare with @rep-chap02-transgender1.\n\n:::\n\n\n:::\n:::\n\n\n\n### Achievement 2: Report frequencies for a factorial variable {#sec-chap02-achievement2}\n\n> Use one of the methods shown to create a table of the frequencies for the HADMAM variable, which indicates whether or not each survey participant had a mammogram. Review the question and response options in the codebook and recode to ensure that the correct category labels show up in the table before you begin.\n\n#### Details of the procedure\n\nI will comply the following procedure\n\n:::::{.my-procedure}\n:::{.my-procedure-header}\n:::::: {#prp-report-fct-variable}\nReport frequencies and proportions for the HADMAM variable\n::::::\n:::\n::::{.my-procedure-container}\n\n1. **Codebook**: Get the appropriate information from the [codebook](https://www.cdc.gov/brfss/annual_data/2014/pdf/CODEBOOK14_LLCP.pdf).\n    - Select variable\n    - Look with `utils::str()` into the attributes to see the labelled variable value\n    - Find with this information the passage in the codebook\n2. **Recode** the variable\n    - Convert the numeric to a categorical variable\n    - Recode levels (include levels for missing values)\n3. **Prepare** recoded variable for table output\n    - Summarize absolute and percentage values with missing data\n    - Summarize absolute and percentage values with missing data\n    - Join both information into a data frame\n\n***\n\nIn addition to check my understand for achievement 2  I will try to show the descriptive statistics as a <a class='glossary' title='Descriptive statistics are often displayed in the first table in a published article or report and are therefore often called Table 1 statistics or the descriptives. (SwR, Harris)'>Table 1</a>, produced with {**kable**} but also with {**gtsummary**}. The table should contain all the features mentioned in @bul-chap02-table-features. I know that this looking ahead of achievement 4, but just let's try it for fun. \n\n4. **Display 1** result with {**knitr**}\n5. **Display 1** result with {**kableExtra**}\n6. **Display 1** result with {**gt**}\n7. **Display 2** result with {**gtsummary**}\n\n***\n\nFinally I have summarized the `HADMAM` variable.\n\n8. **Report 1**: A manual description with copy & paste, always changing between table and document. A method that is very error prone!\n9. **Report 2**: R inline reporting as an R markdown report with the `gtsummary::inline_text()` function. This method results into reproducible reports, an important part of good practices.\n::::\n:::::\n\n#### My solution\n\n:::::{.my-exercise}\n:::{.my-exercise-header}\n:::::: {#exr-chap02-achievement2}\nAchievement 2\n::::::\n:::\n::::{.my-exercise-container}\n\n::: {.panel-tabset}\n\n###### Codebook\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap02-find-codebook}\nFind the codebook\n::::::\n:::\n::::{.my-r-code-container}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## read brfss_tg_2014 data #######\nbrfss_tg_2014 <-  \n    base::readRDS(\"data/chap02/brfss_tg_2014_raw.rds\")\n\n## create hadmam_lab ######\nhadmam_lab <- brfss_tg_2014 |> \n    dplyr::select(HADMAM)\n\nstr(hadmam_lab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> tibble [464,664 × 1] (S3: tbl_df/tbl/data.frame)\n#>  $ HADMAM: num [1:464664] 1 NA NA 1 1 NA NA 1 1 NA ...\n#>   ..- attr(*, \"label\")= chr \"HAVE YOU EVER HAD A MAMMOGRAM\"\n```\n\n\n:::\n:::\n\n***\n\nIn this case the name of the variable HADMAM would have been enough to find the correct passage in the codebook. But this is not always the case. Often the variable name is used many times and it is not often --- like it was the case here --- that the first appearance is the sought one.\n\n::::\n:::::\n\n![Have You Ever Had a\nMammogram?](/img/chap02/mammogram-codebook-min.png){#fig-mammogram-codebook\nfig-alt=\"Table from the Breast and Cervical Cancer Screening. The question asked was: 'A mammogram is an x-ray of each breast to look for breast cancer. Have you ever had a mammogram?'. \n- Yes: 204705 (79.86% resp. 65.86% weighted)\n- No: 51067 (19.92% / 13.86%)\n- Don't know: 253 (0.10% / 0.14%)\n- Refused: 317 (0.12% / 0.14%)\n- Not asked or missing: 208322\" fig-align=\"center\"}\n\n\n###### Recode\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap02-recode-hadmam}\nRecode the `HADMAM` variable\n::::::\n:::\n::::{.my-r-code-container}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## create hadmam_tbl1 #######\nhadmam_tbl1 <- hadmam_lab |> \n    dplyr::mutate(HADMAM = forcats::as_factor(HADMAM)) |> \n    dplyr::mutate(HADMAM = forcats::fct_recode(HADMAM,\n        Yes = '1',\n        No = '2',\n        \"Don't know/Not sure\" = '7',\n        Refused = '9'\n    ))\n\nsummary(hadmam_tbl1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>                  HADMAM      \n#>  Yes                :204705  \n#>  No                 : 51067  \n#>  Don't know/Not sure:   253  \n#>  Refused            :   317  \n#>  NA's               :208322\n```\n\n\n:::\n:::\n\n\n::::\n:::::\n\n###### Prepare\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap02-prepare-hadmam}\n\nPrepare recoded variable `HADMAM` for table output\n::::::\n:::\n::::{.my-r-code-container}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmam1 <- hadmam_tbl1 |> \n    dplyr::group_by(HADMAM) |> \n    dplyr::summarize(freq = dplyr::n()) |> \n    dplyr::mutate(perc = 100 * (base::round(freq / base::sum(freq), 4)))\n\nmam2 <- hadmam_tbl1 |> \n    tidyr::drop_na() |> \n    dplyr::group_by(HADMAM) |> \n    dplyr::summarize(freq = dplyr::n()) |> \n    dplyr::mutate(perc_valid = 100 * (base::round(freq / base::sum(freq), 4)))\n\n## create hadmam_tbl2 ########\nhadmam_tbl2 <- \n    dplyr::full_join(mam1, mam2, \n        dplyr::join_by(HADMAM, freq))\n    \nnames(hadmam_tbl2) <- c(\"Response\", \"n\", \"% with NA's\", \"% without NA's\")\n\nhadmam_tbl2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 5 × 4\n#>   Response                 n `% with NA's` `% without NA's`\n#>   <fct>                <int>         <dbl>            <dbl>\n#> 1 Yes                 204705         44.0             79.9 \n#> 2 No                   51067         11.0             19.9 \n#> 3 Don't know/Not sure    253          0.05             0.1 \n#> 4 Refused                317          0.07             0.12\n#> 5 <NA>                208322         44.8             NA\n```\n\n\n:::\n:::\n\n\n\n::::\n:::::\n\n###### Display 1 \n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap02-display-kable-hadmam}\n\nDisplay HADMAM variable as descriptive statistics with {**kable**}\n\n::::::\n:::\n::::{.my-r-code-container}\n\n\n::: {#tbl-display-kable-hadmam .cell tbl-cap='Have you ever had a mammogram? N = 464664'}\n\n```{.r .cell-code}\nknitr::kable(hadmam_tbl2)\n```\n\n::: {.cell-output-display}\n\n\n|Response            |      n| % with NA's| % without NA's|\n|:-------------------|------:|-----------:|--------------:|\n|Yes                 | 204705|       44.05|          79.86|\n|No                  |  51067|       10.99|          19.92|\n|Don't know/Not sure |    253|        0.05|           0.10|\n|Refused             |    317|        0.07|           0.12|\n|NA                  | 208322|       44.83|             NA|\n\n\n:::\n:::\n\n***\n\nTo get a table with `knitr::kable()` it by far the easiest way: Just put the R dataframe object into the `kable()` function and --- Voilà. And it doesn't look bad!\n\n\n\n::::\n:::::\n\n###### Display 2\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap02-display-kableextra-hadmam}\n\nDisplay HADMAM variable as descriptive statistics with {**kableExtra**}\n\n::::::\n:::\n::::{.my-r-code-container}\n\n\n\n\n\n::: {#tbl-display-kableextra-hadmam .cell tbl-cap='Have you ever had a mammogram? N = 464664'}\n\n```{.r .cell-code}\nhadmam_tbl2 |> \n    kableExtra::kbl() |> \n    kableExtra::kable_classic() |>\n    kableExtra::row_spec(row = 0, bold = TRUE)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\" lightable-classic\" style='font-family: \"Arial Narrow\", \"Source Sans Pro\", sans-serif; margin-left: auto; margin-right: auto;'>\n <thead>\n  <tr>\n   <th style=\"text-align:left;font-weight: bold;\"> Response </th>\n   <th style=\"text-align:right;font-weight: bold;\"> n </th>\n   <th style=\"text-align:right;font-weight: bold;\"> % with NA's </th>\n   <th style=\"text-align:right;font-weight: bold;\"> % without NA's </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> Yes </td>\n   <td style=\"text-align:right;\"> 204705 </td>\n   <td style=\"text-align:right;\"> 44.05 </td>\n   <td style=\"text-align:right;\"> 79.86 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> No </td>\n   <td style=\"text-align:right;\"> 51067 </td>\n   <td style=\"text-align:right;\"> 10.99 </td>\n   <td style=\"text-align:right;\"> 19.92 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Don't know/Not sure </td>\n   <td style=\"text-align:right;\"> 253 </td>\n   <td style=\"text-align:right;\"> 0.05 </td>\n   <td style=\"text-align:right;\"> 0.10 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Refused </td>\n   <td style=\"text-align:right;\"> 317 </td>\n   <td style=\"text-align:right;\"> 0.07 </td>\n   <td style=\"text-align:right;\"> 0.12 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> NA </td>\n   <td style=\"text-align:right;\"> 208322 </td>\n   <td style=\"text-align:right;\"> 44.83 </td>\n   <td style=\"text-align:right;\"> NA </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n***\n\n{**kableExtra**} need more lines to get a similar result as @tbl-display-kable-hadmam. But {**kableExtra**} has many more styling options for HTML but also for {{< latex >}} as you can see in the [extensive documentation](https://haozhu233.github.io/kableExtra/). For instance scroll down the [HTML options page](https://haozhu233.github.io/kableExtra/awesome_table_in_html.html) to get an impression about available features.\n\n\n:::::{.my-watch-out}\n:::{.my-watch-out-header}\nI don't know how to reduce the size of this HTML table and to get rid of the horizontal scroll bar.\n:::\n:::::\n\n::::\n:::::\n\n###### Display 3\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap02-display-gt-hadmam}\n\nDisplay HADMAM variable as descriptive statistics with {**gt**}\n\n::::::\n:::\n::::{.my-r-code-container}\n\n\n::: {#tbl-display-gt-hadmam .cell}\n\n```{.r .cell-code}\nhadmam_tbl2 |> \n    gt::gt() |>\n    gt::tab_caption(\"Have you ever had a mammogram? N = 464664\") |> \n    gt::tab_style(\n        style = gt::cell_text(weight = \"bold\"),\n        locations = gt::cells_column_labels(\n            columns = gt::everything())\n        ) |> \n    gt::tab_style(\n        style = gt::cell_text(align = \"left\"),\n        locations = gt::cells_body(\n            columns = Response\n        )\n    )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"lxyygshgcr\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#lxyygshgcr table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#lxyygshgcr thead, #lxyygshgcr tbody, #lxyygshgcr tfoot, #lxyygshgcr tr, #lxyygshgcr td, #lxyygshgcr th {\n  border-style: none;\n}\n\n#lxyygshgcr p {\n  margin: 0;\n  padding: 0;\n}\n\n#lxyygshgcr .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#lxyygshgcr .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#lxyygshgcr .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#lxyygshgcr .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#lxyygshgcr .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lxyygshgcr .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lxyygshgcr .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lxyygshgcr .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#lxyygshgcr .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#lxyygshgcr .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#lxyygshgcr .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#lxyygshgcr .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#lxyygshgcr .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#lxyygshgcr .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#lxyygshgcr .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#lxyygshgcr .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#lxyygshgcr .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#lxyygshgcr .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#lxyygshgcr .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lxyygshgcr .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#lxyygshgcr .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#lxyygshgcr .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#lxyygshgcr .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lxyygshgcr .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#lxyygshgcr .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#lxyygshgcr .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lxyygshgcr .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lxyygshgcr .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#lxyygshgcr .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lxyygshgcr .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#lxyygshgcr .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lxyygshgcr .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lxyygshgcr .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lxyygshgcr .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lxyygshgcr .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lxyygshgcr .gt_left {\n  text-align: left;\n}\n\n#lxyygshgcr .gt_center {\n  text-align: center;\n}\n\n#lxyygshgcr .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#lxyygshgcr .gt_font_normal {\n  font-weight: normal;\n}\n\n#lxyygshgcr .gt_font_bold {\n  font-weight: bold;\n}\n\n#lxyygshgcr .gt_font_italic {\n  font-style: italic;\n}\n\n#lxyygshgcr .gt_super {\n  font-size: 65%;\n}\n\n#lxyygshgcr .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#lxyygshgcr .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#lxyygshgcr .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#lxyygshgcr .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#lxyygshgcr .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#lxyygshgcr .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#lxyygshgcr .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <caption>Have you ever had a mammogram? N = 464664</caption>\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Response\">Response</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"n\">n</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"% with NA's\">% with NA's</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"% without NA's\">% without NA's</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Response\" class=\"gt_row gt_center\" style=\"text-align: left;\">Yes</td>\n<td headers=\"n\" class=\"gt_row gt_right\">204705</td>\n<td headers=\"% with NA's\" class=\"gt_row gt_right\">44.05</td>\n<td headers=\"% without NA's\" class=\"gt_row gt_right\">79.86</td></tr>\n    <tr><td headers=\"Response\" class=\"gt_row gt_center\" style=\"text-align: left;\">No</td>\n<td headers=\"n\" class=\"gt_row gt_right\">51067</td>\n<td headers=\"% with NA's\" class=\"gt_row gt_right\">10.99</td>\n<td headers=\"% without NA's\" class=\"gt_row gt_right\">19.92</td></tr>\n    <tr><td headers=\"Response\" class=\"gt_row gt_center\" style=\"text-align: left;\">Don't know/Not sure</td>\n<td headers=\"n\" class=\"gt_row gt_right\">253</td>\n<td headers=\"% with NA's\" class=\"gt_row gt_right\">0.05</td>\n<td headers=\"% without NA's\" class=\"gt_row gt_right\">0.10</td></tr>\n    <tr><td headers=\"Response\" class=\"gt_row gt_center\" style=\"text-align: left;\">Refused</td>\n<td headers=\"n\" class=\"gt_row gt_right\">317</td>\n<td headers=\"% with NA's\" class=\"gt_row gt_right\">0.07</td>\n<td headers=\"% without NA's\" class=\"gt_row gt_right\">0.12</td></tr>\n    <tr><td headers=\"Response\" class=\"gt_row gt_center\" style=\"text-align: left;\">NA</td>\n<td headers=\"n\" class=\"gt_row gt_right\">208322</td>\n<td headers=\"% with NA's\" class=\"gt_row gt_right\">44.83</td>\n<td headers=\"% without NA's\" class=\"gt_row gt_right\">NA</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n***\n\nThis is the first time that I used the {**gt**} package. The table looks nice but the construction was super complex: Every change had to be defined in several steps:\n\n(1) what type of change (e.g., table style)\n(2) what type of style (e.g., text of cells)\n(3) what kind of change (e.g., bold)\n(4) where in the table (location e.g., cell body, column labels)\n(5) what element (e.g., everything, a few or just a specific one).\n\n\n::::\n:::::\n\n###### Display 4\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap02-display2-hadmam}\n\nDisplay HADMAM variable as descriptive statistics with {**gtsummary**}\n\n::::::\n:::\n::::{.my-r-code-container}\n\n\n::: {#tbl-display-gtsummary-hadmam .cell tbl-cap='Have you ever had a mammogram? N = 464664'}\n\n```{.r .cell-code}\nm1 <- hadmam_tbl1 |> \n    dplyr::mutate(HADMAM = forcats::as_factor(HADMAM) |> \n        forcats::fct_na_value_to_level(\n            level = \"(Missing)\")) |>\n    gtsummary::tbl_summary(\n        digits = HADMAM ~ c(0, 2)\n    )\n\nm2 <- hadmam_tbl1 |> \n    tidyr::drop_na() |> \n    gtsummary::tbl_summary(\n        digits = HADMAM ~ c(0, 2)\n    )\n\ngtsummary::tbl_merge(\n    list(m1, m2),\n    tab_spanner = c(\"**All values**\", \"**Without missing values**\")\n    )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"liiykzuxmz\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#liiykzuxmz table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#liiykzuxmz thead, #liiykzuxmz tbody, #liiykzuxmz tfoot, #liiykzuxmz tr, #liiykzuxmz td, #liiykzuxmz th {\n  border-style: none;\n}\n\n#liiykzuxmz p {\n  margin: 0;\n  padding: 0;\n}\n\n#liiykzuxmz .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#liiykzuxmz .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#liiykzuxmz .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#liiykzuxmz .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#liiykzuxmz .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#liiykzuxmz .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#liiykzuxmz .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#liiykzuxmz .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#liiykzuxmz .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#liiykzuxmz .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#liiykzuxmz .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#liiykzuxmz .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#liiykzuxmz .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#liiykzuxmz .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#liiykzuxmz .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#liiykzuxmz .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#liiykzuxmz .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#liiykzuxmz .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#liiykzuxmz .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#liiykzuxmz .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#liiykzuxmz .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#liiykzuxmz .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#liiykzuxmz .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#liiykzuxmz .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#liiykzuxmz .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#liiykzuxmz .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#liiykzuxmz .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#liiykzuxmz .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#liiykzuxmz .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#liiykzuxmz .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#liiykzuxmz .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#liiykzuxmz .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#liiykzuxmz .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#liiykzuxmz .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#liiykzuxmz .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#liiykzuxmz .gt_left {\n  text-align: left;\n}\n\n#liiykzuxmz .gt_center {\n  text-align: center;\n}\n\n#liiykzuxmz .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#liiykzuxmz .gt_font_normal {\n  font-weight: normal;\n}\n\n#liiykzuxmz .gt_font_bold {\n  font-weight: bold;\n}\n\n#liiykzuxmz .gt_font_italic {\n  font-style: italic;\n}\n\n#liiykzuxmz .gt_super {\n  font-size: 65%;\n}\n\n#liiykzuxmz .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#liiykzuxmz .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#liiykzuxmz .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#liiykzuxmz .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#liiykzuxmz .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#liiykzuxmz .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#liiykzuxmz .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;All values&lt;/strong&gt;\">\n        <span class=\"gt_column_spanner\"><strong>All values</strong></span>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Without missing values&lt;/strong&gt;\">\n        <span class=\"gt_column_spanner\"><strong>Without missing values</strong></span>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;N = 464,664&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>N = 464,664</strong><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;N = 256,342&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>N = 256,342</strong><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">HADMAM</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Yes</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">204,705 (44.05%)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">204,705 (79.86%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    No</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">51,067 (10.99%)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">51,067 (19.92%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Don't know/Not sure</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">253 (0.05%)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">253 (0.10%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Refused</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">317 (0.07%)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">317 (0.12%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    (Missing)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">208,322 (44.83%)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\"><br /></td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"3\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span> n (%)</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n***\n\nTables with {**gtsummary**} play in another league. They are not constructed for <a class='glossary' title='Data Tables are — in contrast to Display Tables — for analysis and not for presentation. Another purpose of Data Tables is to store, retrieve and share information digitally. In R they are tibbles, data.frames etc.'>data tables</a> but for <a class='glossary' title='Display Tables are in constrast to Data Tables. You would find them in a web page, a journal article, or in a magazine. Such tables are for presentation, often to facilitate the construction of “Table 1”, i.e., baseline characteristics table commonly found in research papers. (Introduction to Creating gt Tables)'>display tables</a>, especially for generating a so-called <a class='glossary' title='Descriptive statistics are often displayed in the first table in a published article or report and are therefore often called Table 1 statistics or the descriptives. (SwR, Harris)'>Table 1</a>. I could therefore not apply my prepared dataset `hadmam_tbl2` but had to use as input the labelled raw data in `hadmam_lab`.\n\n\n::::\n:::::\n\n###### Report 1\n\n\n\n::: {#rep-chap02-mammogram1}\n::: { .callout-tip style=\"color: darkgreen;\"}\n\nThe 2014 phone survey of the <a class='glossary' title='The Behavioral Risk Factor Surveillance System (BRFSS) is a system of health-related telephone surveys that collect state data about U.S. residents regarding their health-related risk behaviors, chronic health conditions, and use of preventive services. Established in 1984 with 15 states, BRFSS now collects data in all 50 states as well as the District of Columbia and three U.S. territories. BRFSS completes more than 400,000 adult interviews each year, making it the largest continuously conducted health survey system in the world. (BRFSS)'>BRFSS</a> (Behavioral Risk Factor Surveillance System) was taken via land-line and cell-phone data. From 464,664 participants were 208,322 (44.83%) people not asked or failed otherwise to respond to the question \"Have You Ever Had a Mammogram?\". Of the 256,342 participants that answered affirmed the vast majority (n = 204,705; 79.86%) the question but still almost one fifth (n = 51,067; 19.92%) never had a mammogram. Some women (n = 253; 0.10%) were not sure or refused an answer (n = 317; 0.12%).\n:::\n\nHave You Ever Had a Mammogram? (Written with copy & paste)\n\n\n:::\n\nCompare my report with the description of a similar structured categorical variable of the same survey: @rep-chap02-transgender2.\n\n###### Report 2\n\n::: {#rep-chap02-mammogram2}\n::: { .callout-tip style=\"color: darkgreen;\"}\n\nThe 2014 phone survey of the <a class='glossary' title='The Behavioral Risk Factor Surveillance System (BRFSS) is a system of health-related telephone surveys that collect state data about U.S. residents regarding their health-related risk behaviors, chronic health conditions, and use of preventive services. Established in 1984 with 15 states, BRFSS now collects data in all 50 states as well as the District of Columbia and three U.S. territories. BRFSS completes more than 400,000 adult interviews each year, making it the largest continuously conducted health survey system in the world. (BRFSS)'>BRFSS</a> (Behavioral Risk Factor Surveillance System) was taken via land-line and cell-phone data. From 464,664 participants were 208,322 (44.83%) people not asked or failed otherwise to respond to the question \"Have You Ever Had a Mammogram?\". The vast majority of the 256,342 participants affirmed the question  204,705 (79.86%), but still 51,067 (19.92%) --- that is almost one fifth --- never had a mammogram. A small amount of women 253 (0.10%) were not sure  and some women 317 (0.12%) refused an answer.\n:::\n\nHave You Ever Had a Mammogram? (Written with `gtsummary::inline_text()`)\n\n\n:::\n\nI had to reformulate some text part, because the replacement was always `<absolute number> (<percent number>%)`. But that was not a big deal. The advantage of `gtsummary::inline_text()` summaries are reproducible reports that prevents errors in copy & paste *and* are adapted automatically if the figures of the table changes!\n\nCompare this report with the copy & paste description from @rep-chap02-mammogram1.\n:::\n\n::::\n:::::\n\n***\n\n## Descriptive analyses for continuous (numeric) variables {#sec-chap02-describe-numeric-variables}\n\n### Skewness\n\n<a class='glossary' title='Skewness is the extent to which a variable has extreme values in one of the two tails of its distribution (SwR, Glossary)'>Skewness</a> is a measure of the extent to which a distribution is skewed.\n\n$$\nskewness_x = \\frac{1}{n}\\sum_{i=1}^{n}(\\frac{x_i - m_x}{s_x})^3\n$$ {#eq-chap02-skewness}\n\nThe mean of $x$, $m_x$, is subtracted from each observation $x_i$. These differences between the mean and each observed value are called <a class='glossary' title='Deviation scores show the difference from some value like the mean; for example, z-scores show the deviation from the mean in standard deviation units'>deviation scores</a>. Each deviation score is divided by the <a class='glossary' title='The standard deviation is a measure of the amount of variation or dispersion of a set of values. A low standard deviation indicates that the values tend to be close to the mean (also called the expected value) of the set, while a high standard deviation indicates that the values are spread out over a wider range. The standard deviation is the square root of its variance. A useful property of the standard deviation is that, unlike the variance, it is expressed in the same unit as the data. Standard deviation may be abbreviated SD, and is most commonly represented in mathematical texts and equations by the lower case Greek letter \\(\\sigma\\) (sigma), for the population standard deviation, or the Latin letter \\(s\\) for the sample standard deviation. (Wikipedia)'>standard deviation</a>, $s$, and the result is cubed. Finally, sum the cubed values and divide by the number of cubed values (which is taking the mean) to get the <a class='glossary' title='Skewness is the extent to which a variable has extreme values in one of the two tails of its distribution (SwR, Glossary)'>skewness</a> of $x$. The resulting value is usually negative when the skew is to the left and usually positive when the skew is toward the right. Skewness is strongly impacted by the sample size, therefore the value of skew that is considered too skewed differs depending on sample size.\n\nThere are many packages to compute the skewness of a distribution. (Type `??skewness` into the console to get a list. Harris recommends the `skew()` function from the {**semTools**} package. \n\n***\n\n::: {#pak-semTools}\n\n***\n\n{**semTools**}: [Useful Tools for Structural Equation Modeling](https://github.com/simsem/semTools/wiki)\n\n(For {**semTools**} there is currently no logo available.)\n\nProvides tools for structural equation modeling, many of which extend the {**lavaan**} package; for example, to pool results from multiple imputations, probe latent interactions, or test measurement invariance.\n***\n\n{**semTools**}: A Package for Useful Tools for Structural Equation Modeling\n:::\n\nThis is a very specialized package. I believe I will not use it at the moment besides the function `semTools::skew()` and `semTools::kurtosis()`.\n\n***\n\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap02-check-skew}\n: Using the `skew()` function from {**semTools**}\n::::::\n:::\n::::{.my-r-code-container}\n\n::: {#lst-chap02-check-skewness}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsalaries <- c(25000, 62000, 41000, 96000, 41000)\nsalaries_gates <- c(salaries, 11500000000)\n\nsemTools::skew(salaries)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> skew (g1)        se         z         p \n#> 1.1111306 1.0954451 1.0143188 0.3104306\n```\n\n\n:::\n\n```{.r .cell-code}\nsemTools::skew(salaries_gates)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>  skew (g1)         se          z          p \n#> 2.44948974 1.00000000 2.44948974 0.01430588\n```\n\n\n:::\n:::\n\n\nUsing the `skew()` function from {**semTools**}\n\n:::\n\n***\n\n- **skew (g1)**: <a class='glossary' title='Skewness is the extent to which a variable has extreme values in one of the two tails of its distribution (SwR, Glossary)'>Skewness</a>\n- **se**: <a class='glossary' title='The standard error (se) is a measure of variability that estimates how much variability there is in a population based on the variability in the sample and the size of the sample. (SwR, Glossary)'>Standard error</a>\n- **z**: <a class='glossary' title='A z-score (also called a standard score) gives you an idea of how far from the mean a data point is. But more technically it’s a measure of how many standard deviations below or above the population mean a raw score is. (StatisticsHowTo)'>Z-score</a>\n- **p**: <a class='glossary' title='The p-value is the probability that the test statistic is at least as big as it is under the null hypothesis (SwR, Glossary)'>p-value</a>\n\n::::\n:::::\n\n:::::{.my-assessment}\n:::{.my-assessment-header}\n:::::: {#cor-chap02-skewness}\n: Assessment of skewness\n::::::\n:::\n::::{.my-assessment-container}\n\n| Sample Size    |       Z-values Range      | Comment                         |\n|----------------|:-------------------------:|---------------------------------|\n| n < 50         |    under -2 or over +2    | Problem!                        |\n| n > 50 & < 300 | under -3.29 or over +3.29 | Problem!                        |\n| n > 300        |     under -7 or over 7    | Problem but visual recommended! |\n: Skewness assessment {#tbl-chap02-skewness} {.striped .hover}\n\n***\n\nHarris referenced [@kim2013] for the assessment table above. I noticed that there are many [short articles about different types of test.](https://synapse.koreamed.org/advanced/index.php). Just put the search string \"Statistical[ALL] AND notes[ALL] AND clinical[ALL] AND researchers[ALL]\" into the Kamje search engine.\n\nThe z result of code @lst-chap02-check-skewness from the `salaries_gates` vector is 2.45, i.e., over 2 and therefore we have a skewness problem. The other vector, without the salary of Bill Gates is not excessively skewed.\n\n::::\n:::::\n\n### Data management for numerical variable\n\n:::::{.my-example}\n:::{.my-example-header}\n:::::: {#exm-chap02-data-wrangling-numerical}\n: Data management for numerical variable\n::::::\n:::\n::::{.my-example-container}\n\n::: {.panel-tabset}\n\n###### Codebook\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap02-codebook-physical-health}\nFind numerical variable `PHYSHLTH` in codebook \n::::::\n:::\n::::{.my-r-code-container}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrfss_tg_2014 <- base::readRDS(\"data/chap02/brfss_tg_2014_raw.rds\")\n\nphysical_health <- brfss_tg_2014 |> \n    dplyr::select(PHYSHLTH)\n\nstr(physical_health)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> tibble [464,664 × 1] (S3: tbl_df/tbl/data.frame)\n#>  $ PHYSHLTH: num [1:464664] 25 7 88 77 2 5 2 3 88 1 ...\n#>   ..- attr(*, \"label\")= chr \"NUMBER OF DAYS PHYSICAL HEALTH NOT GOOD\"\n```\n\n\n:::\n:::\n\n\n***\n\n![How many days during the past 30 days was your physical health not good?](img/chap02/physical-health-codebook-min.png){#fig-physical-health-codebook\nfig-alt=\"Table about health status from BEHAVIORAL RISK FACTOR SURVEILLANCE SYSTEM\nCODEBOOK REPORT (BRFSS), 2014\" fig-align=\"center\"}\n\n***\n\n::::\n:::::\n\n\n###### Recode\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-chap02-recode-physical-health}\nRecode numerical variable `PHYSHLTH`\n::::::\n:::\n::::{.my-r-code-container}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphysical_health_clean <- physical_health\n```\n:::\n\n\n::::\n:::::\n\n:::\n\n::::\n:::::\n\n***\n\n## Glossary\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> term </th>\n   <th style=\"text-align:left;\"> definition </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> Backtick </td>\n   <td style=\"text-align:left;\"> The backtick ` is a typographical mark used mainly in computing. It is also known as backquote, grave, or grave accent. (<a href=\"https://en.wikipedia.org/wiki/Backtick\">Wikipedia</a>) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> BRFSS </td>\n   <td style=\"text-align:left;\"> The Behavioral Risk Factor Surveillance System (BRFSS) is a system of health-related telephone surveys that collect state data about U.S. residents regarding their health-related risk behaviors, chronic health conditions, and use of preventive services. Established in 1984 with 15 states, BRFSS now collects data in all 50 states as well as the District of Columbia and three U.S. territories. BRFSS completes more than 400,000 adult interviews each year, making it the largest continuously conducted health survey system in the world. (<a href=\"https://www.cdc.gov/brfss/index.html\">BRFSS</a>) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Cisgender </td>\n   <td style=\"text-align:left;\"> People whose gender identity matches their biological sex. Contrast: Transgender (SwR, Harris) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CSV </td>\n   <td style=\"text-align:left;\"> Text files where the values are separated with commas (Comma Separated Values = CSV). These files have the file extension .csv </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Data Tables </td>\n   <td style=\"text-align:left;\"> Data Tables are --- in contrast to Display Tables --- for analysis and not for presentation. Another purpose of Data Tables is to store, retrieve and share information digitally. In R they are tibbles, data.frames etc. </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Deviation Scores </td>\n   <td style=\"text-align:left;\"> Deviation scores show the difference from some value like the mean; for example, z-scores show the deviation from the mean in standard deviation units </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Display Tables </td>\n   <td style=\"text-align:left;\"> Display Tables are in constrast to Data Tables. You would find them in a web page, a journal article, or in a magazine. Such tables are for presentation, often to facilitate the construction of “Table 1”, i.e., baseline characteristics table commonly found in research papers. (<a href=\"https://gt.rstudio.com/articles/gt.html\">Introduction to Creating gt Tables</a>) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Gender Nonconforming </td>\n   <td style=\"text-align:left;\"> Gender nonconforming means not adhering to society's gender norms. People may describe themselves as gender nonconforming if they don't conform to the gender expression, presentation, behaviors, roles, or expectations that society sees as the norm for their gender. ([APA Guidelines - PDF](https://www.apa.org/practice/guidelines/transgender.pdf)) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Labelled Data </td>\n   <td style=\"text-align:left;\"> Labelled data (or labelled vectors) is a common data structure in other statistical environments to store meta-information about variables, like variable names, value labels or multiple defined missing values. (<a href=\"https://strengejacke.github.io/sjlabelled/articles/intro_sjlabelled.html\">sjlabelled</a>) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> p-value </td>\n   <td style=\"text-align:left;\"> The p-value is the probability that the test statistic is at least as big as it is under the null hypothesis (SwR, Glossary) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Skewness </td>\n   <td style=\"text-align:left;\"> Skewness is the extent to which a variable has extreme values in one of the two tails of its distribution (SwR, Glossary) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Standard Deviation </td>\n   <td style=\"text-align:left;\"> The standard deviation is a measure of the amount of variation or dispersion of a set of values. A low standard deviation indicates that the values tend to be close to the mean (also called the expected value) of the set, while a high standard deviation indicates that the values are spread out over a wider range. The standard deviation is the square root of its variance. A useful property of the standard deviation is that, unlike the variance, it is expressed in the same unit as the data. Standard deviation may be abbreviated SD, and is most commonly represented in mathematical texts and equations by the lower case Greek letter $\\sigma$ (sigma), for the population standard deviation, or the Latin letter $s$ for the sample standard deviation. ([Wikipedia](https://en.wikipedia.org/wiki/Standard_deviation)) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Standard Error </td>\n   <td style=\"text-align:left;\"> The standard error (se) is a measure of variability that estimates how much variability there is in a population based on the variability in the sample and the size of the sample. (SwR, Glossary) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Table 1 </td>\n   <td style=\"text-align:left;\"> Descriptive statistics are often displayed in the first table in a published article or report and are therefore often called <i>Table 1 statistics</i> or the <i>descriptives</i>. (SwR, Harris) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Transgender </td>\n   <td style=\"text-align:left;\"> People whose biological sex is not consistent with their gender. Contrast: Cisgender (SwR, Harris) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Z-score </td>\n   <td style=\"text-align:left;\"> A z-score (also called a standard score) gives you an idea of how far from the mean a data point is. But more technically it’s a measure of how many standard deviations below or above the population mean a raw score is. (<a href=\"https://www.statisticshowto.com/probability-and-statistics/z-score/#Whatisazscore\">StatisticsHowTo</a>) </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## Session Info {.unnumbered}\n\n::: my-r-code\n::: my-r-code-header\nSession Info\n:::\n\n::: my-r-code-container\n\n::: {.cell}\n\n```{.r .cell-code}\nsessioninfo::session_info()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> ─ Session info ───────────────────────────────────────────────────────────────\n#>  setting  value\n#>  version  R version 4.3.2 (2023-10-31)\n#>  os       macOS Sonoma 14.2.1\n#>  system   x86_64, darwin20\n#>  ui       X11\n#>  language (EN)\n#>  collate  en_US.UTF-8\n#>  ctype    en_US.UTF-8\n#>  tz       Europe/Vienna\n#>  date     2024-01-24\n#>  pandoc   3.1.11.1 @ /usr/local/bin/ (via rmarkdown)\n#> \n#> ─ Packages ───────────────────────────────────────────────────────────────────\n#>  package       * version    date (UTC) lib source\n#>  backports       1.4.1      2021-12-13 [1] CRAN (R 4.3.0)\n#>  base64enc       0.1-3      2015-07-28 [1] CRAN (R 4.3.0)\n#>  broom.helpers   1.14.0     2023-08-07 [1] CRAN (R 4.3.0)\n#>  checkmate       2.3.1      2023-12-04 [1] CRAN (R 4.3.0)\n#>  cli             3.6.2      2023-12-11 [1] CRAN (R 4.3.0)\n#>  cluster         2.1.6      2023-12-01 [1] CRAN (R 4.3.2)\n#>  coda            0.19-4     2020-09-30 [1] CRAN (R 4.3.0)\n#>  codetools       0.2-19     2023-02-01 [2] CRAN (R 4.3.2)\n#>  colorspace      2.1-0      2023-01-23 [1] CRAN (R 4.3.0)\n#>  commonmark      1.9.0      2023-03-17 [1] CRAN (R 4.3.0)\n#>  curl            5.2.0      2023-12-08 [1] CRAN (R 4.3.2)\n#>  data.table      1.14.10    2023-12-08 [1] CRAN (R 4.3.0)\n#>  datawizard      0.9.1      2023-12-21 [1] CRAN (R 4.3.0)\n#>  descr           1.1.8      2023-11-27 [1] CRAN (R 4.3.0)\n#>  digest          0.6.34     2024-01-11 [1] CRAN (R 4.3.0)\n#>  dplyr           1.1.4      2023-11-17 [1] CRAN (R 4.3.0)\n#>  emmeans         1.9.0      2023-12-18 [1] CRAN (R 4.3.0)\n#>  estimability    1.4.1      2022-08-05 [1] CRAN (R 4.3.0)\n#>  evaluate        0.23       2023-11-01 [1] CRAN (R 4.3.0)\n#>  fansi           1.0.6      2023-12-08 [1] CRAN (R 4.3.0)\n#>  fastmap         1.1.1      2023-02-24 [1] CRAN (R 4.3.0)\n#>  forcats         1.0.0      2023-01-29 [1] CRAN (R 4.3.0)\n#>  foreign         0.8-86     2023-11-28 [1] CRAN (R 4.3.2)\n#>  Formula         1.2-5      2023-02-24 [1] CRAN (R 4.3.0)\n#>  generics        0.1.3      2022-07-05 [1] CRAN (R 4.3.0)\n#>  ggplot2         3.4.4      2023-10-12 [1] CRAN (R 4.3.0)\n#>  glossary      * 1.0.0.9000 2023-08-12 [1] Github (debruine/glossary@819e329)\n#>  glue            1.7.0      2024-01-09 [1] CRAN (R 4.3.0)\n#>  gridExtra       2.3        2017-09-09 [1] CRAN (R 4.3.0)\n#>  gt              0.10.1     2024-01-17 [1] CRAN (R 4.3.0)\n#>  gtable          0.3.4      2023-08-21 [1] CRAN (R 4.3.0)\n#>  gtsummary       1.7.2      2023-07-15 [1] CRAN (R 4.3.0)\n#>  here            1.0.1      2020-12-13 [1] CRAN (R 4.3.0)\n#>  highr           0.10       2022-12-22 [1] CRAN (R 4.3.0)\n#>  Hmisc           5.1-1      2023-09-12 [1] CRAN (R 4.3.0)\n#>  htmlTable       2.4.2      2023-10-29 [1] CRAN (R 4.3.0)\n#>  htmltools       0.5.7      2023-11-03 [1] CRAN (R 4.3.0)\n#>  htmlwidgets     1.6.4      2023-12-06 [1] CRAN (R 4.3.0)\n#>  httr            1.4.7      2023-08-15 [1] CRAN (R 4.3.0)\n#>  insight         0.19.7     2023-11-26 [1] CRAN (R 4.3.0)\n#>  jsonlite        1.8.8      2023-12-04 [1] CRAN (R 4.3.0)\n#>  kableExtra      1.3.4      2021-02-20 [1] CRAN (R 4.3.0)\n#>  knitr           1.45       2023-10-30 [1] CRAN (R 4.3.0)\n#>  lattice         0.22-5     2023-10-24 [2] CRAN (R 4.3.0)\n#>  lavaan          0.6-17     2023-12-20 [1] CRAN (R 4.3.0)\n#>  lifecycle       1.0.4      2023-11-07 [1] CRAN (R 4.3.0)\n#>  magrittr        2.0.3      2022-03-30 [1] CRAN (R 4.3.0)\n#>  markdown        1.12       2023-12-06 [1] CRAN (R 4.3.0)\n#>  MASS            7.3-60.0.1 2024-01-13 [2] CRAN (R 4.3.0)\n#>  Matrix          1.6-5      2024-01-11 [1] CRAN (R 4.3.0)\n#>  mnormt          2.1.1      2022-09-26 [1] CRAN (R 4.3.0)\n#>  multcomp        1.4-25     2023-06-20 [1] CRAN (R 4.3.0)\n#>  munsell         0.5.0      2018-06-12 [1] CRAN (R 4.3.0)\n#>  mvtnorm         1.2-4      2023-11-27 [1] CRAN (R 4.3.2)\n#>  nnet            7.3-19     2023-05-03 [2] CRAN (R 4.3.2)\n#>  pbivnorm        0.6.0      2015-01-23 [1] CRAN (R 4.3.0)\n#>  pillar          1.9.0      2023-03-22 [1] CRAN (R 4.3.0)\n#>  pkgconfig       2.0.3      2019-09-22 [1] CRAN (R 4.3.0)\n#>  purrr           1.0.2      2023-08-10 [1] CRAN (R 4.3.0)\n#>  quadprog        1.5-8      2019-11-20 [1] CRAN (R 4.3.0)\n#>  R6              2.5.1      2021-08-19 [1] CRAN (R 4.3.0)\n#>  report          0.5.8      2023-12-07 [1] CRAN (R 4.3.0)\n#>  rlang           1.1.3      2024-01-10 [1] CRAN (R 4.3.0)\n#>  rmarkdown       2.25       2023-09-18 [1] CRAN (R 4.3.0)\n#>  rpart           4.1.23     2023-12-05 [2] CRAN (R 4.3.0)\n#>  rprojroot       2.0.4      2023-11-05 [1] CRAN (R 4.3.0)\n#>  rstudioapi      0.15.0     2023-07-07 [1] CRAN (R 4.3.0)\n#>  rversions       2.1.2      2022-08-31 [1] CRAN (R 4.3.0)\n#>  rvest           1.0.3      2022-08-19 [1] CRAN (R 4.3.0)\n#>  sandwich        3.1-0      2023-12-11 [1] CRAN (R 4.3.0)\n#>  sass            0.4.8      2023-12-06 [1] CRAN (R 4.3.0)\n#>  scales          1.3.0      2023-11-28 [1] CRAN (R 4.3.2)\n#>  semTools        0.5-6      2022-05-10 [1] CRAN (R 4.3.0)\n#>  sessioninfo     1.2.2      2021-12-06 [1] CRAN (R 4.3.0)\n#>  stringi         1.8.3      2023-12-11 [1] CRAN (R 4.3.0)\n#>  stringr         1.5.1      2023-11-14 [1] CRAN (R 4.3.0)\n#>  survival        3.5-7      2023-08-14 [2] CRAN (R 4.3.2)\n#>  svglite         2.1.3      2023-12-08 [1] CRAN (R 4.3.0)\n#>  systemfonts     1.0.5      2023-10-09 [1] CRAN (R 4.3.0)\n#>  TH.data         1.1-2      2023-04-17 [1] CRAN (R 4.3.0)\n#>  tibble          3.2.1      2023-03-20 [1] CRAN (R 4.3.0)\n#>  tidyr           1.3.0      2023-01-24 [1] CRAN (R 4.3.0)\n#>  tidyselect      1.2.0      2022-10-10 [1] CRAN (R 4.3.0)\n#>  utf8            1.2.4      2023-10-22 [1] CRAN (R 4.3.0)\n#>  vctrs           0.6.5      2023-12-01 [1] CRAN (R 4.3.2)\n#>  viridisLite     0.4.2      2023-05-02 [1] CRAN (R 4.3.0)\n#>  webshot         0.5.5      2023-06-26 [1] CRAN (R 4.3.0)\n#>  withr           3.0.0      2024-01-16 [1] CRAN (R 4.3.0)\n#>  xfun            0.41       2023-11-01 [1] CRAN (R 4.3.0)\n#>  xml2            1.3.6      2023-12-04 [1] CRAN (R 4.3.0)\n#>  xtable          1.8-4      2019-04-21 [1] CRAN (R 4.3.0)\n#>  yaml            2.3.8      2023-12-11 [1] CRAN (R 4.3.0)\n#>  zoo             1.8-12     2023-04-13 [1] CRAN (R 4.3.0)\n#> \n#>  [1] /Library/Frameworks/R.framework/Versions/4.3-x86_64/library\n#>  [2] /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library\n#> \n#> ──────────────────────────────────────────────────────────────────────────────\n```\n\n\n:::\n:::\n\n:::\n:::\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}